(() => {
  const widgets = [
    ['hero','▶','Aktueller Titel','Aktuelle Wiedergabe'],['search','⌕','Suche','Musik suchen'],['radio','◉','Radio','Radiosender'],['system','◒','Systemauslastung','CPU, RAM, Netzwerk'],['queue','☷','Warteschlange','Nächste Titel'],['discord','◌','Discord','Discord-Status'],['ts3','◍','TeamSpeak 3','TS3-Status'],['media','♫','Medien','Mediensteuerung'],['playlists','≡','Playlists','Wiedergabelisten'],['spotify','●','Spotify','Spotify-Status'],['youtube','▶','YouTube','YouTube-Status'],['update','↻','Aktualisierungen','Version & Updates'],['quick','✦','Schnellzugriff','Direkte Aktionen'],['mode','◐','Wiedergabemodus','Lautstärke & Modus']
  ];
  let toolbar, builderOpen=false, saveTimer=0;
  const api=async(url,options={})=>{const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;};
  const toast=message=>{const n=document.createElement('div');n.className='widget-builder-toast';n.textContent=message;document.body.appendChild(n);setTimeout(()=>n.remove(),2200);};
  function tileContainer(){return document.querySelector('[data-tile]')?.parentElement||null;}
  function currentOrder(){const c=tileContainer();return c?[...c.querySelectorAll(':scope > [data-tile]')].map(e=>e.dataset.tile).filter(Boolean):[];}
  function persist(order){clearTimeout(saveTimer);saveTimer=window.setTimeout(async()=>{try{await api('/api/ui/layout',{method:'PUT',body:JSON.stringify({order})});toast('Layout gespeichert');}catch(e){toast(`Layout konnte nicht gespeichert werden: ${e.message}`);}},120);}
  function addRemoveButtons(container){container.querySelectorAll(':scope > [data-tile]').forEach(tile=>{const head=tile.querySelector('.tile-head');if(!head||head.querySelector('.widget-remove'))return;const b=document.createElement('button');b.type='button';b.className='widget-remove';b.textContent='Entfernen';b.title='Widget vom Dashboard entfernen';b.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();if(!confirm('Widget vom Dashboard entfernen?'))return;tile.remove();persist(currentOrder());});head.appendChild(b);});}
  async function addWidget(id){const order=currentOrder();if(order.includes(id)){toast('Dieses Widget ist bereits auf dem Dashboard.');return;}order.push(id);try{await api('/api/ui/layout',{method:'PUT',body:JSON.stringify({order})});toast('Widget hinzugefügt');window.go?.('dashboard');}catch(e){toast(`Widget konnte nicht hinzugefügt werden: ${e.message}`);}}
  function createToolbar(){toolbar=document.createElement('aside');toolbar.id='widgetBuilderToolbar';toolbar.className='widget-builder-toolbar';toolbar.innerHTML=`<div class="widget-builder-head"><div><strong>Dashboard-Baukasten</strong><small>Widgets per Drag & Drop platzieren</small></div><button class="widget-builder-close" type="button" aria-label="Baukasten schließen">×</button></div><div class="widget-palette"></div><div class="widget-builder-actions"><button type="button" class="ghost" data-builder-reset>Zurücksetzen</button><button type="button" class="primary" data-builder-save>Speichern</button></div><div class="widget-builder-hint">Ziehe ein Widget aus der Liste auf das Dashboard. Vorhandene Kacheln kannst du neu sortieren oder entfernen.</div>`;document.body.appendChild(toolbar);const p=toolbar.querySelector('.widget-palette');widgets.forEach(([id,icon,title,hint])=>{const item=document.createElement('div');item.className='widget-palette-item';item.draggable=true;item.dataset.widgetId=id;item.innerHTML=`<span class="widget-palette-icon">${icon}</span><span class="widget-palette-text"><b>${title}</b><span>${hint}</span></span>`;item.addEventListener('dragstart',e=>{e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('application/x-musikbot-widget',id);item.classList.add('widget-palette-dragging');});item.addEventListener('dragend',()=>item.classList.remove('widget-palette-dragging'));item.addEventListener('dblclick',()=>addWidget(id));p.appendChild(item);});toolbar.querySelector('.widget-builder-close').addEventListener('click',closeBuilder);toolbar.querySelector('[data-builder-save]').addEventListener('click',()=>persist(currentOrder()));toolbar.querySelector('[data-builder-reset]').addEventListener('click',async()=>{const defaults=['hero','discord','search','radio','system','queue','media','playlists','spotify','youtube','update'];try{await api('/api/ui/layout',{method:'PUT',body:JSON.stringify({order:defaults})});toast('Standard-Layout wiederhergestellt');window.go?.('dashboard');}catch(e){toast(e.message);}});}
  function openBuilder(){if(!toolbar)createToolbar();const c=tileContainer();if(!c)return toast('Der Dashboard-Baukasten ist nur auf der Startseite verfügbar.');builderOpen=true;document.body.classList.add('dashboard-builder-active');toolbar.classList.add('open');addRemoveButtons(c);}
  function closeBuilder(){builderOpen=false;document.body.classList.remove('dashboard-builder-active');toolbar?.classList.remove('open');}
  function ensureButton(){const top=document.querySelector('.top-actions');const dash=document.querySelector('[data-tile]');if(!top||!dash){document.querySelector('#widgetBuilderButton')?.classList.remove('visible');if(!dash)closeBuilder();return;}let b=document.querySelector('#widgetBuilderButton');if(!b){b=document.createElement('button');b.id='widgetBuilderButton';b.className='widget-builder-button icon-btn';b.type='button';b.title='Dashboard-Baukasten';b.textContent='✦';b.addEventListener('click',()=>builderOpen?closeBuilder():openBuilder());top.insertBefore(b,top.querySelector('#settingsQuick')||null);}b.classList.add('visible');if(builderOpen)addRemoveButtons(tileContainer());}
  document.addEventListener('dragover',e=>{const id=e.dataTransfer?.types?.includes('application/x-musikbot-widget');if(!id)return;const c=tileContainer();if(!c)return;e.preventDefault();if(!e.target.closest('[data-tile]'))c.classList.add('widget-drop-placeholder');});
  document.addEventListener('drop',async e=>{const id=e.dataTransfer?.getData('application/x-musikbot-widget');if(!id)return;const c=tileContainer();c?.classList.remove('widget-drop-placeholder');if(!c)return;e.preventDefault();await addWidget(id);});
  document.addEventListener('dragend',()=>document.querySelectorAll('.widget-drop-placeholder').forEach(x=>x.classList.remove('widget-drop-placeholder')));
  new MutationObserver(ensureButton).observe(document.body,{childList:true,subtree:true});
  ensureButton();
})();
