#!/usr/bin/env python3
from pathlib import Path
ROOT=Path('/opt/radiobot')
backend=ROOT/'backend/src/index.ts'; metrics=ROOT/'scripts/system-metrics.py'; metrics_js=ROOT/'frontend/metrics-panel.js'; app_js=ROOT/'frontend/app.js'
s=backend.read_text(encoding='utf-8')

def rep(old,new,label,required=True):
    global s
    if old in s:
        s=s.replace(old,new,1)
    elif required:
        raise SystemExit(f'missing hardening marker: {label}')

rep("await app.register(cors, { origin: true });","await app.register(cors, { origin: false });","cors")
rep("const YTDLP = process.env.YTDLP_PATH ?? '/usr/local/bin/yt-dlp';","const YTDLP = process.env.YTDLP_PATH ?? '/usr/local/bin/yt-dlp';\nconst REQUEST_LIMIT = 240;\nconst RATE_WINDOW_MS = 60_000;\nconst requestBuckets = new Map<string, { start: number; count: number }>();\nconst playLocks = new Map<string, Promise<void>>();","security state")
rep("function loadJson<T>(file: string, fallback: T): T { try { return JSON.parse(fs.readFileSync(file, 'utf8')) as T; } catch { return fallback; } }","function loadJson<T>(file: string, fallback: T): T { try { return JSON.parse(fs.readFileSync(file, 'utf8')) as T; } catch (error) { try { if (fs.existsSync(file)) fs.renameSync(file, `${file}.corrupt-${Date.now()}`); } catch {} console.error(`Invalid JSON in ${file}; preserved corrupt file`, error); return fallback; } }","loadJson")
rep("function saveJson(file: string, value: unknown) { fs.writeFileSync(file, JSON.stringify(value, null, 2), { mode: 0o600 }); }","function saveJson(file: string, value: unknown) { const tmp = `${file}.${process.pid}.tmp`; fs.writeFileSync(tmp, JSON.stringify(value, null, 2), { mode: 0o600 }); fs.renameSync(tmp, file); }","saveJson")
rep("function auth(req: any, reply: any) {\n  if (!WEB_PASSWORD) return true;\n  const h = String(req.headers.authorization ?? '');\n  if (!h.startsWith('Basic ')) { reply.header('WWW-Authenticate', 'Basic realm=\"RadioBot\"').code(401).send('Authentication required'); return false; }\n  const d = Buffer.from(h.slice(6), 'base64').toString('utf8'); const i = d.indexOf(':');\n  const u = i >= 0 ? d.slice(0, i) : ''; const p = i >= 0 ? d.slice(i + 1) : '';\n  if (u !== WEB_USER || p !== WEB_PASSWORD) { reply.header('WWW-Authenticate', 'Basic realm=\"RadioBot\"').code(401).send('Invalid credentials'); return false; }\n  return true;\n}","function auth(req: any, reply: any) {\n  if (!WEB_PASSWORD) { reply.code(503).send('Web authentication is not configured'); return false; }\n  const origin = String(req.headers.origin ?? '');\n  if (origin) { const host = String(req.headers.host ?? ''); if (origin !== `http://${host}` && origin !== `https://${host}`) { reply.code(403).send('Origin not allowed'); return false; } }\n  const h = String(req.headers.authorization ?? '');\n  if (!h.startsWith('Basic ')) { reply.header('WWW-Authenticate', 'Basic realm=\"RadioBot\"').code(401).send('Authentication required'); return false; }\n  let d = ''; try { d = Buffer.from(h.slice(6), 'base64').toString('utf8'); } catch { reply.code(401).send('Invalid credentials'); return false; }\n  const i = d.indexOf(':'); const u = i >= 0 ? d.slice(0, i) : ''; const p = i >= 0 ? d.slice(i + 1) : '';\n  if (u !== WEB_USER || p !== WEB_PASSWORD) { reply.header('WWW-Authenticate', 'Basic realm=\"RadioBot\"').code(401).send('Invalid credentials'); return false; }\n  return true;\n}","auth")
rep("const old = connections.get(guildId);\n  if (old && old.state.status !== VoiceConnectionStatus.Destroyed) return old;","const old = connections.get(guildId);\n  if (old && [VoiceConnectionStatus.Ready, VoiceConnectionStatus.Connecting, VoiceConnectionStatus.Signalling].includes(old.state.status)) return old;\n  if (old) { try { old.destroy(); } catch {} connections.delete(guildId); }","voice recovery")
rep("    const ffmpeg = spawn('ffmpeg', args, { stdio: ['ignore', 'pipe', 'inherit'] }); ffmpegs.set(guildId, ffmpeg);","    const ffmpeg = spawn('ffmpeg', args, { stdio: ['ignore', 'pipe', 'inherit'] });\n    ffmpeg.once('error', error => console.error('ffmpeg spawn failed', guildId, error));\n    ffmpegs.set(guildId, ffmpeg);","ffmpeg error")
rep("    console.error('playback failed', guildId, error); state.playing = undefined; state.playingType = undefined; saveJson(DB_FILE, db); await updateStatus(guildId); await playNext(guildId);","    console.error('playback failed', guildId, error); state.playing = undefined; state.playingType = undefined; saveJson(DB_FILE, db); await updateStatus(guildId);","playback recursion removal")
rep("  const items = playlist.items.map(item => ({ kind: item.kind, value: item.value, label: item.label, playlistName: playlist.name } as QueueItem));\n  const state = guildState(guildId); if (replace) { await stopGuild(guildId); state.activePlaylistId = playlist.id; state.queue = items; } else state.queue.push(...items); saveJson(DB_FILE, db); await updateStatus(guildId); if (!state.playing) await playNext(guildId); return state;","  let items = playlist.items.map(item => ({ kind: item.kind, value: item.value, label: item.label, playlistName: playlist.name } as QueueItem));\n  const state = guildState(guildId); state.activePlaylistId = playlist.id; if (state.shuffle) items = items.sort(() => Math.random() - 0.5); if (replace) { await stopGuild(guildId); state.manualStop = false; state.queue = items; } else state.queue.push(...items); saveJson(DB_FILE, db); await updateStatus(guildId); if (!state.playing) await playNext(guildId); return state;","queue playlist")
rep("async function playNext(guildId: string) {","async function playNextUnlocked(guildId: string) {","playback function rename")
# Replace the unlock-safe function body around the first queue item lookup with a bounded loop.
rep("  const state = guildState(guildId);\n  let item = state.queue.shift();","  const state = guildState(guildId);\n  let failed = 0;\n  while (failed < 20) {\n  let item = state.queue.shift();","playback loop start")
rep("    }\n  }\n}\n\nasync function stopGuild(guildId: string) {","    }\n    failed += 1;\n  }\n}\n\nasync function playNext(guildId: string) {\n  const running = playLocks.get(guildId);\n  if (running) return running;\n  const run = playNextUnlocked(guildId).finally(() => { if (playLocks.get(guildId) === run) playLocks.delete(guildId); });\n  playLocks.set(guildId, run);\n  return run;\n}\n\nasync function stopGuild(guildId: string) {","playback lock")
rep("const state = guildState(guildId); state.manualStop = true; state.queue = []; state.playing = undefined; state.playingType = undefined; state.currentPlaylist = undefined; state.activePlaylistId = undefined; state.lastItem = undefined;","const state = guildState(guildId); state.manualStop = true; state.queue = []; state.playing = undefined; state.playingType = undefined; state.currentPlaylist = undefined; state.activePlaylistId = undefined; state.lastItem = undefined;","stop state")
# Direct play/replace endpoints must stop first; append continues current playback.
rep("app.post<{ Params: { id: string }; Body: { radioId: string; append?: boolean } }>('/api/state/:id/radio', async req => { const r = db.radios.find(x => x.id === req.body.radioId); if (!r) throw new Error('Radio nicht gefunden.'); const s = enqueue(req.params.id, { kind: 'radio', value: r.url, label: r.name, playlistName: `Radio: ${r.name}` }, !req.body.append); if (!s.playing) await playNext(req.params.id); return s; });","app.post<{ Params: { id: string }; Body: { radioId: string; append?: boolean } }>('/api/state/:id/radio', async req => { const r = db.radios.find(x => x.id === req.body.radioId); if (!r) throw new Error('Radio nicht gefunden.'); if (!req.body.append) await stopGuild(req.params.id); const s = enqueue(req.params.id, { kind: 'radio', value: r.url, label: r.name, playlistName: `Radio: ${r.name}` }, false); s.manualStop = false; if (!s.playing) await playNext(req.params.id); return s; });","radio replace")
rep("app.post<{ Params: { id: string }; Body: { file: string; append?: boolean } }>('/api/state/:id/file', async req => { const file = mediaPath(req.body.file); if (!fs.existsSync(file)) throw new Error('Datei nicht gefunden.'); const s = enqueue(req.params.id, { kind: 'file', value: req.body.file, label: req.body.file, playlistName: 'Direkt / Lokal' }, !req.body.append); if (!s.playing) await playNext(req.params.id); return s; });","app.post<{ Params: { id: string }; Body: { file: string; append?: boolean } }>('/api/state/:id/file', async req => { if (!req.body.file || req.body.file.length > 255) throw new Error('Ungültige Mediendatei.'); const file = mediaPath(req.body.file); if (!fs.existsSync(file)) throw new Error('Datei nicht gefunden.'); if (!req.body.append) await stopGuild(req.params.id); const s = enqueue(req.params.id, { kind: 'file', value: req.body.file, label: req.body.file, playlistName: 'Direkt / Lokal' }, false); s.manualStop = false; if (!s.playing) await playNext(req.params.id); return s; });","file replace")
rep("app.post('/api/update', async (_req, reply) => {","app.post('/api/update', async (req, reply) => {","update route")
rep("const openSetup = req.url.startsWith('/api/setup'); if (req.url.startsWith('/api/') && !openSetup && !req.url.startsWith('/api/spotify/callback') && !auth(req, reply)) return reply;","const openSetup = req.url.startsWith('/api/setup') || req.url.startsWith('/api/health') || req.url.startsWith('/api/spotify/callback'); if (req.url.startsWith('/api/') && !openSetup && !auth(req, reply)) return reply; const key = String(req.ip ?? 'unknown'); const now = Date.now(); const bucket = requestBuckets.get(key); if (!bucket || now - bucket.start >= RATE_WINDOW_MS) requestBuckets.set(key, { start: now, count: 1 }); else { bucket.count += 1; if (bucket.count > REQUEST_LIMIT) return reply.code(429).send('Too many requests'); }","security hook")
# Guard costly searches and user-provided strings.
rep("app.get<{ Querystring: { q?: string } }>('/api/search', async req => { const q = String(req.query.q ?? '').trim(); if (!q) return { local: [], radios: [], youtube: [], spotify: [] }; return unifiedSearch(q); });","app.get<{ Querystring: { q?: string } }>('/api/search', async req => { const q = String(req.query.q ?? '').trim(); if (q.length > 200) return reply.code(400).send('Suchbegriff zu lang.'); if (!q) return { local: [], radios: [], youtube: [], spotify: [] }; return unifiedSearch(q); });","search limit",required=False)
# Repair the search route if its handler has no reply parameter.
s=s.replace("app.get<{ Querystring: { q?: string } }>('/api/search', async req => { const q = String(req.query.q ?? '').trim(); if (q.length > 200) return reply.code(400).send('Suchbegriff zu lang.'); if (!q) return { local: [], radios: [], youtube: [], spotify: [] }; return unifiedSearch(q); });","app.get<{ Querystring: { q?: string } }>('/api/search', async (req, reply) => { const q = String(req.query.q ?? '').trim(); if (q.length > 200) return reply.code(400).send('Suchbegriff zu lang.'); if (!q) return { local: [], radios: [], youtube: [], spotify: [] }; return unifiedSearch(q); });",1)
# Fix web settings blank-field preservation and expose non-secret values for the form.
s=s.replace("app.get('/api/settings', async () => ({ webUser: WEB_USER, port: PORT, spotifyConfigured: Boolean(SPOTIFY_CLIENT_ID && SPOTIFY_CLIENT_SECRET), youtubeConfigured: Boolean(YOUTUBE_API_KEY), controlRole: DISCORD_CONTROL_ROLE, redirectUri: SPOTIFY_REDIRECT_URI }));","app.get('/api/settings', async () => ({ webUser: WEB_USER, port: PORT, spotifyClientId: SPOTIFY_CLIENT_ID, spotifyConfigured: Boolean(SPOTIFY_CLIENT_ID && SPOTIFY_CLIENT_SECRET), youtubeConfigured: Boolean(YOUTUBE_API_KEY), controlRole: DISCORD_CONTROL_ROLE, redirectUri: SPOTIFY_REDIRECT_URI }));",1)
s=s.replace("spotifyClientId: b.spotifyClientId?.trim() ?? SPOTIFY_CLIENT_ID, spotifyClientSecret: b.spotifyClientSecret?.trim() ?? SPOTIFY_CLIENT_SECRET, spotifyRedirectUri: b.spotifyRedirectUri?.trim() ?? SPOTIFY_REDIRECT_URI, youtubeApiKey: b.youtubeApiKey?.trim() ?? YOUTUBE_API_KEY, discordControlRole: b.discordControlRole?.trim() ?? DISCORD_CONTROL_ROLE, publicUrl: b.publicUrl?.trim() || '',","spotifyClientId: b.spotifyClientId?.trim() || SPOTIFY_CLIENT_ID, spotifyClientSecret: b.spotifyClientSecret?.trim() || SPOTIFY_CLIENT_SECRET, spotifyRedirectUri: b.spotifyRedirectUri?.trim() || SPOTIFY_REDIRECT_URI, youtubeApiKey: b.youtubeApiKey?.trim() || YOUTUBE_API_KEY, discordControlRole: b.discordControlRole?.trim() || DISCORD_CONTROL_ROLE, publicUrl: b.publicUrl?.trim() || '',",1)
# Make Discord commands that stop-then-start clear the manual stop latch.
s=s.replace("await stopGuild(interaction.guildId); enqueue(interaction.guildId, { kind: item.kind, value: item.value, label: item.label, playlistName: 'Direkt' }, true); await playNext(interaction.guildId);","await stopGuild(interaction.guildId); state.manualStop = false; enqueue(interaction.guildId, { kind: item.kind, value: item.value, label: item.label, playlistName: 'Direkt' }, true); await playNext(interaction.guildId);",1)
s=s.replace("await stopGuild(interaction.guildId); enqueue(interaction.guildId, { kind: 'radio', value: radio.url, label: radio.name, playlistName: `Radio: ${radio.name}` }, true); await playNext(interaction.guildId);","await stopGuild(interaction.guildId); state.manualStop = false; enqueue(interaction.guildId, { kind: 'radio', value: radio.url, label: radio.name, playlistName: `Radio: ${radio.name}` }, true); await playNext(interaction.guildId);",1)
# Add/update YouTube route after the final replacement logic.
if "/api/state/:id/youtube" not in s:
    needle="app.post<{ Params: { id: string }; Body: { file: string; append?: boolean } }>('/api/state/:id/file'"
    route="app.post<{ Params: { id: string }; Body: { value: string; label?: string; append?: boolean } }>('/api/state/:id/youtube', async req => { const value = req.body.value?.trim(); if (!value || value.length > 1000) throw new Error('Ungültige YouTube-Quelle.'); if (!req.body.append) await stopGuild(req.params.id); const s = enqueue(req.params.id, { kind: 'youtube', value, label: req.body.label?.trim() || value, playlistName: 'Direkt / YouTube' }, false); s.manualStop = false; if (!s.playing) await playNext(req.params.id); return s; });\n"
    s=s.replace(needle, route+needle,1)
# Keep metrics protected by the common API auth hook; make the saved file itself private.
backend.write_text(s,encoding='utf-8')
metrics.write_text(metrics.read_text(encoding='utf-8').replace("OUT = Path('/opt/radiobot/frontend/metrics.json')","OUT = Path('/var/lib/radiobot/metrics.json')",1),encoding='utf-8')
metrics_js.write_text(metrics_js.read_text(encoding='utf-8').replace("fetch('/metrics.json'","fetch('/api/metrics'",1),encoding='utf-8')
old="if (x.kind === 'youtube') { return fetch('/api/playlists', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ name:`_search_${Date.now()}`, kind:'youtube', items:[{ kind:'youtube', value:x.value, label:x.label }] }) }).then(r=>r.json()).then(p=>api(`/api/playlists/${p.id}/play/${guildId}`, { method:'POST', body:JSON.stringify({ append }) })); }"
new="if (x.kind === 'youtube') return api(`/api/state/${guildId}/youtube`, { method:'POST', body:JSON.stringify({ value:x.value, label:x.label, append }) });"
app_js.write_text(app_js.read_text(encoding='utf-8').replace(old,new,1),encoding='utf-8')
helper=Path('/usr/local/sbin/radiobot-configure')
if helper.exists():
    c=helper.read_text(encoding='utf-8').replace("        current[key]=value\n","        if key in {'WEB_PASSWORD','SPOTIFY_CLIENT_SECRET','YOUTUBE_API_KEY','DISCORD_TOKEN'} and value == '' and current.get(key):\n            continue\n        current[key]=value\n",1)
    helper.write_text(c,encoding='utf-8')
print('final hardening applied')
