import test from "node:test";
import assert from "node:assert/strict";
import http from "node:http";
import path from "node:path";
import { readFile } from "node:fs/promises";
import { encryptSecret, decryptSecret } from "../backend/src/secrets.js";
import { validateResolvedMediaUrl } from "../backend/src/source-policy.js";
import { EgressProxy } from "../backend/src/egress-proxy.js";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");

test("secrets are encrypted at rest and decrypt losslessly", async () => { const plain = "ts3-super-secret-123"; const encrypted = await encryptSecret(plain); assert.notEqual(encrypted, plain); assert.match(encrypted, /^enc\$/); assert.equal(await decryptSecret(encrypted), plain); });
test("egress proxy blocks loopback before opening an upstream socket", async () => { const proxy = await new EgressProxy().start(); try { const status = await new Promise(resolve => { const request = http.request({ hostname: "127.0.0.1", port: proxy.port, path: "http://127.0.0.1:1/test", method: "GET" }, response => { response.resume(); resolve(response.statusCode); }); request.once("error", error => resolve(error.code === "ECONNRESET" ? 502 : 599)); request.end(); }); assert.equal(status, 502); } finally { await proxy.stop(); } });
test("source policy rejects reserved final media targets", async () => { await assert.rejects(() => validateResolvedMediaUrl("http://127.0.0.1:3000/audio"), /nicht erlaubtes Netzwerkziel/); });
test("server and player route external playback through bounded policy paths", async () => { const server = await readFile(path.join(root, "backend/src/server.js"), "utf8"); const player = await readFile(path.join(root, "backend/src/player.js"), "utf8"); assert.match(server, /app\.post\("\/api\/logout"/); assert.match(server, /bodyLimit: MAX_JSON_BODY/); assert.match(server, /consumeLimit\(`search:/); assert.match(server, /await encryptSecret\(String\(x\.password\)/); assert.match(server, /settings\.filesDirectory = path\.relative/); assert.match(server, /return \{ url: env \?/); assert.match(server, /readSignature\(target\)/); assert.match(player, /validateResolvedMediaUrl\(url\)/); assert.match(player, /-http_proxy/); assert.match(player, /ensureEgressProxy\(\)/); });
test("installer has a pinned release fetch, binary checksum and isolated service", async () => { const installer = await readFile(path.join(root, "install-stable.sh"), "utf8"); assert.match(installer, /git -C \"\$APP\" fetch --depth 1 origin \"\$REF\"/); assert.match(installer, /releases\/download\//); assert.match(installer, /sha256sum -c/); assert.match(installer, /NoNewPrivileges=true/); assert.match(installer, /CapabilityBoundingSet=/); assert.doesNotMatch(installer, /NOPASSWD/); assert.doesNotMatch(installer, /sudoers\.d\/musikbot187/); });
test("frontend has one central fetch wrapper and lifecycle cleanup", async () => { const files = ["frontend/fetch-layer.js", "frontend/app.js", "frontend/enhancements.js", "frontend/errorlog.js", "frontend/music-ui.js"]; let wrappers = 0; for (const file of files) wrappers += (await readFile(path.join(root, file), "utf8")).match(/window\.fetch\s*=\s*async/g)?.length || 0; assert.equal(wrappers, 1); const html = await readFile(path.join(root, "frontend/index.html"), "utf8"); assert.match(html, /fetch-layer\.js/); const cleanup = await readFile(path.join(root, "frontend/system-cleanup.js"), "utf8"); assert.match(cleanup, /window\.setInterval/); });
test("coalesced dashboard requests return the same JSON shape as normal requests", async () => { const performance = await readFile(path.join(root, "frontend/performance.js"), "utf8"); assert.match(performance, /const result = await hit\.pending/); assert.match(performance, /cloneJsonResponse\(result\.body, result\.status\)/); assert.doesNotMatch(performance, /cloneJsonResponse\(await hit\.pending\)/); });
test("Discord volume changes use the live resource instead of restarting audio", async () => { const discord = await readFile(path.join(root, "backend/src/discord.js"), "utf8"); const writeAudio = discord.slice(discord.indexOf("  writeAudio(data, id)")); assert.match(discord, /inlineVolume: true/); assert.match(discord, /resource\.volume\.setVolume/); assert.doesNotMatch(writeAudio, /resetAudioStream\(id\)/); });
test("player emits raw PCM with volume metadata so output adapters own volume processing", async () => { const player = await readFile(path.join(root, "backend/src/player.js"), "utf8"); const ts3 = await readFile(path.join(root, "backend/src/ts3.js"), "utf8"); assert.match(player, /rawAudio\(Buffer\.from\(d\), this\.volume\)/); assert.doesNotMatch(player, /scalePcm16/); assert.match(ts3, /data\.__musikbotVolume/); });
test("YouTube playback forces web_embedded to avoid cross-client GVS 403s", async () => { const player = await readFile(path.join(root, "backend/src/player.js"), "utf8"); assert.match(player, /youtube:player_client=web_embedded/); assert.doesNotMatch(player, /youtube:player_client=default,web_embedded/); assert.doesNotMatch(player, /player_client=web_safari/); assert.match(player, /-f\", \"bestaudio\/best/); });
test("search play is handled by the current immediate-play fix", async () => { const fix = await readFile(path.join(root, "frontend/search-play-fix.js"), "utf8"); const layer = await readFile(path.join(root, "frontend/fetch-layer.js"), "utf8"); const index = await readFile(path.join(root, "frontend/index.html"), "utf8"); assert.match(fix, /playNow: true/); assert.match(fix, /stopImmediatePropagation\(\)/); assert.match(layer, /getLastSearch\(\)/); assert.match(index, /search-play-fix\.js/); });
test("playlist reorder is atomic and playlist playback replaces the current queue", async () => { const server = await readFile(path.join(root, "backend/src/server.js"), "utf8"); const playlist = await readFile(path.join(root, "frontend/playlist-ui.js"), "utf8"); assert.match(server, /app\.put\("\/api\/playlists\/:id"/); assert.match(server, /playNow: true/); assert.match(playlist, /put\(`\/api\/playlists/); assert.doesNotMatch(playlist, /for \(const item of playlist\.items\) await del/); });
test("Discord reconnect guard is live and TS3 reconnect keeps configuration", async () => { const discord = await readFile(path.join(root, "backend/src/discord.js"), "utf8"); const ts3 = await readFile(path.join(root, "backend/src/ts3.js"), "utf8"); assert.match(discord, /manualDisconnecting/); assert.match(discord, /if \(!runtime \|\| runtime\.manualDisconnecting \|\| runtime\.reconnectTimer/); assert.match(discord, /scheduleGatewayReconnect\(runtime\)/); assert.match(discord, /runtime\.manualDisconnecting = true/); assert.match(ts3, /disconnect\(key, true\)/); assert.match(ts3, /scheduleReconnect\(key\)/); });
test("Discord editor provides invite and voice actions and uses canonical save fields", async () => { const app = await readFile(path.join(root, "frontend/app.js"), "utf8"); const fix = await readFile(path.join(root, "frontend/discord-select-fix.js"), "utf8"); const actions = await readFile(path.join(root, "frontend/discord-instance-actions.js"), "utf8"); assert.match(app, /inviteUrl\(clientId\)/); assert.match(actions, /data-dbot-invite/); assert.match(actions, /data-dvoice-join/); assert.match(fix, /Bot hinzufügen/); assert.match(fix, /Voice-Chat betreten/); assert.match(fix, /window\.open\(url, '_blank'/); assert.match(fix, /channelId:/); assert.match(fix, /method: 'POST'[\s\S]*\/api\/discord/); });
