import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {autoplayTermSearchQuery,autoplayTermSuggestions,validateAutoplayTermEvidence} from '../backend/src/autoplay.js';
import {buildServer} from '../backend/src/server.js';

test('Autoplay keeps verified genre and artist evidence separate and offers matching suggestions',()=>{assert.equal(validateAutoplayTermEvidence('Gabber',[],'genre').matched,'Hardcore');assert.equal(validateAutoplayTermEvidence('Hardtech',[{title:'Hardtech Festival Official Audio'}],'genre').valid,true);assert.equal(validateAutoplayTermEvidence('Hardtech',[{title:'Hard Techno Festival'}],'genre').valid,false);assert.equal(validateAutoplayTermEvidence('Rammstein',[{title:'Rammstein – Sonne (Official Audio)'}],'artist').valid,true);assert.equal(validateAutoplayTermEvidence('Ramm',[{title:'Rammstein – Sonne (Official Audio)'}],'artist').valid,false);assert.ok(autoplayTermSuggestions('Hard',[],'genre').some(item=>item.value==='Hardstyle'&&item.type==='genre'));assert.ok(autoplayTermSuggestions('Ramm',[{title:'Rammstein – Sonne (Official Audio)'}],'artist').some(item=>item.value==='Rammstein'&&item.type==='artist'));assert.ok(autoplayTermSuggestions('Gabber',[],'genre').some(item=>item.value==='Hardcore'));assert.match(autoplayTermSearchQuery('Rammstein','artist'),/Rammstein.*Künstler/);assert.match(autoplayTermSearchQuery('Hardtech','genre'),/Hardtech.*Musikrichtung/)});

test('Autoplay API verifies new genres and artists before saving them',async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'musikbot187-autoplay-validation-')),queries=[],provider=async query=>{queries.push(query);if(/Hardtech/i.test(query))return[{title:'Hardtech Music Festival 2026'}];if(/Ramm/i.test(query))return[{title:'Rammstein – Sonne (Official Audio)'}];return[{title:'Völlig anderer Künstler – Pop Song'}]},app=await buildServer({dataDir:dir,musicDir:path.join(dir,'music'),stateFile:path.join(dir,'state.json'),secretFile:path.join(dir,'secret.key'),frontendDir:path.resolve('frontend'),setupToken:'setup-test-token',logger:false,controlSocket:path.join(dir,'control.sock'),autoplayStyleValidationProvider:provider});t.after(async()=>{await app.close();await fs.rm(dir,{recursive:true,force:true})});let response=await app.inject({method:'POST',url:'/api/setup',headers:{'x-musikbot-setup-token':'setup-test-token'},payload:{username:'admin',password:'correct-horse-battery'}}),headers={authorization:`Bearer ${response.json().token}`};
  response=await app.inject({method:'POST',url:'/api/autoplay/profile/term/validate',headers,payload:{term:'Hardstyle',kind:'genre'}});assert.equal(response.statusCode,200,response.body);assert.equal(response.json().type,'genre');assert.equal(queries.length,0);
  response=await app.inject({method:'POST',url:'/api/autoplay/profile/term/validate',headers,payload:{term:'Hard',kind:'genre'}});assert.equal(response.statusCode,200,response.body);assert.equal(response.json().valid,false);assert.ok(response.json().suggestions.some(item=>item.value==='Hardstyle'));assert.equal(queries.length,0);
  response=await app.inject({method:'POST',url:'/api/autoplay/profile/term/validate',headers,payload:{term:'Hardtech',kind:'genre'}});assert.equal(response.statusCode,200,response.body);assert.equal(response.json().valid,true);assert.match(response.json().evidence[0],/Hardtech/);
  response=await app.inject({method:'POST',url:'/api/autoplay/profile/term/validate',headers,payload:{term:'Ramm',kind:'artist'}});assert.equal(response.statusCode,200,response.body);assert.equal(response.json().valid,false);assert.ok(response.json().suggestions.some(item=>item.value==='Rammstein'));
  response=await app.inject({method:'POST',url:'/api/autoplay/profile/term/validate',headers,payload:{term:'Rammstein',kind:'artist'}});assert.equal(response.statusCode,200,response.body);assert.equal(response.json().valid,true);assert.equal(response.json().matched,'Rammstein');
  response=await app.inject({method:'PUT',url:'/api/autoplay/profile/styles',headers,payload:{preferredStyles:['Hardtech'],preferredArtists:['Rammstein'],blockedStyles:['Schlager']}});assert.equal(response.statusCode,200,response.body);assert.deepEqual(response.json().profile.preferredStyles,['Hardtech']);assert.deepEqual(response.json().profile.preferredArtists,['Rammstein']);assert.deepEqual(response.json().profile.blockedStyles,['Schlager']);
  response=await app.inject({method:'PUT',url:'/api/autoplay/profile/styles',headers,payload:{preferredStyles:['Erfundener Stil'],preferredArtists:['Rammstein'],blockedStyles:['Schlager']}});assert.equal(response.statusCode,400,response.body);assert.match(response.json().error,/keine passende Musikrichtung/);
  response=await app.inject({method:'PUT',url:'/api/autoplay/profile/styles',headers,payload:{preferredStyles:['Hardtech'],preferredArtists:['Erfundener Künstler'],blockedStyles:['Schlager']}});assert.equal(response.statusCode,400,response.body);assert.match(response.json().error,/kein passender Künstler/);
  const saved=JSON.parse(await fs.readFile(path.join(dir,'state.json'),'utf8')).listeningProfile;assert.deepEqual(saved.preferredStyles,['Hardtech']);assert.deepEqual(saved.preferredArtists,['Rammstein']);assert.deepEqual(saved.blockedStyles,['Schlager']);
});
