import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createBackupFile,removeBackupWork,restoreBackupFile} from '../backend/src/backup.js';
import {buildServer} from '../backend/src/server.js';
import {Store} from '../backend/src/store.js';
import {SecretBox,hashPassword,verifyPassword} from '../backend/src/security.js';

test('existing installations are migrated as already onboarded',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'musikbot-existing-')),file=path.join(dir,'state.json');t.after(()=>fs.rm(dir,{recursive:true,force:true}));await fs.writeFile(file,JSON.stringify({version:2,users:[{id:'owner',username:'owner',passwordHash:hashPassword('existing-owner-password'),role:'admin',permissions:[]}],sessions:[],settings:{botName:'Bestehender Bot'},diagnostics:[]}));const store=await new Store(file).load();assert.equal(store.data.settings.setupCompleted,true)});

test('encrypted full backup restores local music and non-owner accounts but never the owner',async t=>{
  const sourceDir=await fs.mkdtemp(path.join(os.tmpdir(),'musikbot-backup-source-')),targetDir=await fs.mkdtemp(path.join(os.tmpdir(),'musikbot-backup-target-'));t.after(async()=>{await fs.rm(sourceDir,{recursive:true,force:true});await fs.rm(targetDir,{recursive:true,force:true})});
  const sourceStore=new Store(path.join(sourceDir,'state.json')),sourceKey=crypto.randomBytes(32).toString('hex'),sourceSecrets=SecretBox.fromHex(sourceKey);sourceStore.data.users.push({id:'old-owner',username:'old-owner',passwordHash:hashPassword('old-owner-password'),role:'admin',permissions:[]},{id:'listener',username:'listener',passwordHash:hashPassword('listener-password'),role:'user',permissions:['player.control']});sourceStore.data.settings.setupCompleted=true;sourceStore.data.settings.spotifySecret=sourceSecrets.seal('spotify-secret');sourceStore.data.connections.push({id:'discord-one',type:'discord',name:'Discord',secret:sourceSecrets.seal('discord-secret')});sourceStore.data.playlists.push({id:'mix',name:'Mix',items:[{title:'Lokaler Titel',source:'local',path:'sample.mp3'}]});await fs.mkdir(path.join(sourceDir,'music'),{recursive:true});await fs.writeFile(path.join(sourceDir,'music','sample.mp3'),'audio-data');await sourceStore.save();
  const result=await createBackupFile({store:sourceStore,dataDir:sourceDir,musicDir:path.join(sourceDir,'music'),secretKey:sourceKey,password:'very-secure-backup-password'});const importedPath=path.join(targetDir,'incoming.mb187'),wrongPath=path.join(targetDir,'wrong-password.mb187');await fs.copyFile(result.path,importedPath);await fs.copyFile(result.path,wrongPath);await removeBackupWork(result);
  const targetStore=new Store(path.join(targetDir,'state.json')),targetKey=crypto.randomBytes(32).toString('hex'),targetSecrets=SecretBox.fromHex(targetKey);targetStore.data.users.push({id:'new-owner',username:'new-owner',passwordHash:hashPassword('new-owner-password'),role:'admin',permissions:[]});targetStore.data.sessions.push({tokenHash:'active',userId:'new-owner',created:Date.now(),expires:Date.now()+60_000});await targetStore.save();
  await assert.rejects(restoreBackupFile({inputPath:wrongPath,password:'wrong-backup-password',store:targetStore,dataDir:targetDir,musicDir:path.join(targetDir,'music'),targetSecrets,maxBytes:128*1024*1024}),/Passwort falsch|beschädigt/);const restored=await restoreBackupFile({inputPath:importedPath,password:'very-secure-backup-password',store:targetStore,dataDir:targetDir,musicDir:path.join(targetDir,'music'),targetSecrets,maxBytes:128*1024*1024});assert.equal(restored.users,1);assert.deepEqual(targetStore.data.users.map(user=>user.username),['new-owner','listener']);assert.equal(verifyPassword('listener-password',targetStore.data.users[1].passwordHash),true);assert.equal(targetSecrets.open(targetStore.data.settings.spotifySecret),'spotify-secret');assert.equal(targetSecrets.open(targetStore.data.connections[0].secret),'discord-secret');assert.equal(await fs.readFile(path.join(targetDir,'music','sample.mp3'),'utf8'),'audio-data');assert.equal(targetStore.data.settings.setupCompleted,false);assert.equal(targetStore.data.sessions.length,1);
});

test('notifications remain unread after the banner poll and can be read or deleted per user',async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'musikbot-notifications-')),app=await buildServer({dataDir:dir,musicDir:path.join(dir,'music'),stateFile:path.join(dir,'state.json'),secretFile:path.join(dir,'secret.key'),frontendDir:path.resolve('frontend'),setupToken:'setup-test-token',logger:false,updateFetcher:async()=>({ok:true,status:200,json:async()=>({version:'1.8.8'})})});t.after(async()=>{await app.close();await fs.rm(dir,{recursive:true,force:true})});
  let response=await app.inject({method:'POST',url:'/api/setup',headers:{'x-musikbot-setup-token':'setup-test-token'},payload:{username:'admin',password:'correct-horse-battery'}}),headers={authorization:`Bearer ${response.json().token}`};await app.inject({url:'/api/system/update',headers});response=await app.inject({url:'/api/notifications',headers});assert.equal(response.statusCode,200,response.body);let update=response.json().items.find(item=>item.type==='update');assert.ok(update);assert.equal(update.unread,true);response=await app.inject({method:'PUT',url:`/api/notifications/${update.id}/read`,headers});assert.equal(response.statusCode,200,response.body);await app.inject({url:'/api/system/update',headers});response=await app.inject({url:'/api/notifications',headers});assert.equal(response.json().items.find(item=>item.id===update.id).unread,false);
  await app.inject({method:'POST',url:'/api/diagnostics/client',headers,payload:{context:'Test',message:'Absichtlicher Testfehler'}});response=await app.inject({url:'/api/notifications',headers});const diagnostic=response.json().items.find(item=>item.type==='diagnostic');assert.ok(diagnostic);assert.equal(diagnostic.target,'diagnostics');response=await app.inject({method:'DELETE',url:`/api/notifications/${diagnostic.id}`,headers});assert.equal(response.statusCode,200,response.body);response=await app.inject({url:'/api/notifications',headers});assert.equal(response.json().items.some(item=>item.id===diagnostic.id),false);
  response=await app.inject({method:'POST',url:'/api/backup/export',headers,payload:{password:'download-backup-password'}});assert.equal(response.statusCode,200,response.body);const downloadToken=response.json().downloadToken;response=await app.inject({url:`/api/backup/download/${downloadToken}`});assert.equal(response.statusCode,200,response.body);assert.equal(response.rawPayload.subarray(0,9).toString('ascii'),'MB187BKP1');assert.match(response.headers['content-disposition'],/MusikBot187-\d{4}-\d{2}-\d{2}\.mb187/);assert.equal((await app.inject({url:`/api/backup/download/${downloadToken}`})).statusCode,404);
});

test('update notifications are checked in the background, deduplicated and removed when current',async t=>{
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'musikbot-update-background-')),stateFile=path.join(dir,'state.json');let latest='1.8.8',fetches=0;const app=await buildServer({dataDir:dir,musicDir:path.join(dir,'music'),stateFile,secretFile:path.join(dir,'secret.key'),frontendDir:path.resolve('frontend'),logger:false,updateCheckStartupDelayMs:20,updateCheckIntervalMs:30,updateFetcher:async()=>{fetches++;return {ok:true,status:200,json:async()=>({version:latest})}}});t.after(async()=>{await app.close();await fs.rm(dir,{recursive:true,force:true})});
  const notifications=async()=>{try{return JSON.parse(await fs.readFile(stateFile,'utf8')).notifications||[]}catch{return []}},waitFor=async predicate=>{const timeout=Date.now()+2000;while(Date.now()<timeout){const value=await predicate();if(value)return value;await new Promise(resolve=>setTimeout(resolve,20))}assert.fail('Automatische Update-Prüfung wurde nicht rechtzeitig sichtbar.')};
  await waitFor(async()=>{const items=await notifications();return items.some(item=>item.type==='update'&&item.dedupeKey==='update:1.8.8')});await new Promise(resolve=>setTimeout(resolve,120));let items=await notifications();assert.equal(items.filter(item=>item.type==='update').length,1);assert.ok(fetches>=2);latest='1.8.7';await waitFor(async()=>!(await notifications()).some(item=>item.type==='update'));items=await notifications();assert.equal(items.some(item=>item.type==='update'),false);
});
