import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {buildServer} from '../backend/src/server.js';

async function fixture(options={}){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'musikbot187-report-api-')),app=await buildServer({dataDir:dir,musicDir:path.join(dir,'music'),stateFile:path.join(dir,'state.json'),secretFile:path.join(dir,'secret.key'),frontendDir:path.resolve('frontend'),setupToken:'setup-test-token',logger:false,controlSocket:path.join(dir,'control.sock'),...options});return {dir,app}}
async function setup(app){const response=await app.inject({method:'POST',url:'/api/setup',headers:{'x-musikbot-setup-token':'setup-test-token'},payload:{username:'admin',password:'correct-horse-battery'}});return response.json().token}
async function multipart(fields,file){const form=new FormData();for(const[key,value]of Object.entries(fields))form.set(key,value);if(file)form.append('files',new Blob([file.data],{type:file.type}),file.name);const request=new Request('http://local.test/api/bug-report',{method:'POST',body:form});return {payload:Buffer.from(await request.arrayBuffer()),contentType:request.headers.get('content-type')}}

test('every authenticated user can send a bounded sanitized report without reading diagnostics',async t=>{
  let delivered;const {app,dir}=await fixture({bugReportRelayUrl:'https://support.example/reports',bugReportSender:async input=>{delivered=input;return {ok:true,id:input.report.id}}});t.after(async()=>{await app.close();await fs.rm(dir,{recursive:true,force:true})});const owner=await setup(app),ownerHeaders={authorization:`Bearer ${owner}`};
  await app.inject({method:'POST',url:'/api/diagnostics/client',headers:ownerHeaders,payload:{context:'Test',message:'token=secret-value jonas@example.com 192.168.0.25'}});let response=await app.inject({method:'POST',url:'/api/users',headers:ownerHeaders,payload:{username:'reporter',role:'user',permissions:[]}}),temporary=response.json().temporaryPassword;response=await app.inject({method:'POST',url:'/api/auth/login',payload:{username:'reporter',password:temporary}});let userHeaders={authorization:`Bearer ${response.json().token}`};response=await app.inject({method:'POST',url:'/api/auth/password',headers:userHeaders,payload:{current:temporary,next:'reporter-personal-password'}});userHeaders={authorization:`Bearer ${response.json().token}`};
  assert.equal((await app.inject({url:'/api/diagnostics',headers:userHeaders})).statusCode,403);response=await app.inject({url:'/api/bug-report/info',headers:userHeaders});assert.equal(response.statusCode,200,response.body);assert.equal(response.json().enabled,true);
  const body=await multipart({description:'Die Wiedergabe stoppt nach dem Start immer sofort und ohne Hinweis.',category:'playback',context:'Dashboard',includeDiagnostics:'true'},{name:'fehler.png',type:'image/png',data:Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0])});response=await app.inject({method:'POST',url:'/api/bug-report',headers:{...userHeaders,'content-type':body.contentType},payload:body.payload});assert.equal(response.statusCode,200,response.body);assert.match(response.json().id,/^MB187-\d{8}-[A-F0-9]{8}$/);assert.equal(response.json().attachments,1);assert.equal(delivered.report.reporterRole,'user');assert.equal(delivered.files.length,1);assert.doesNotMatch(JSON.stringify(delivered.report.diagnostics),/secret-value|jonas@example|192\.168/);
});

test('bug reporting stays disabled when the relay URL is explicitly cleared',async t=>{const {app,dir}=await fixture({bugReportRelayUrl:''});t.after(async()=>{await app.close();await fs.rm(dir,{recursive:true,force:true})});const token=await setup(app),headers={authorization:`Bearer ${token}`};let response=await app.inject({url:'/api/bug-report/info',headers});assert.equal(response.json().enabled,false);response=await app.inject({method:'POST',url:'/api/bug-report',headers});assert.equal(response.statusCode,503);assert.match(response.json().error,/eingerichtet/)});

test('invalid attachments do not consume the hourly support-report allowance',async t=>{
  let delivered=0;const {app,dir}=await fixture({bugReportRelayUrl:'https://support.example/reports',bugReportSender:async({report})=>{delivered++;return {ok:true,id:report.id}}});t.after(async()=>{await app.close();await fs.rm(dir,{recursive:true,force:true})});const token=await setup(app),headers={authorization:`Bearer ${token}`},fields={description:'Dieser gültige Testbericht muss trotz vorheriger Dateifehler versendet werden.',category:'problem',context:'Dashboard',includeDiagnostics:'true'};
  for(let attempt=0;attempt<4;attempt++){const invalid=await multipart(fields,{name:'protokoll.txt',type:'text/plain',data:Buffer.from('kein Bild')});const response=await app.inject({method:'POST',url:'/api/bug-report',headers:{...headers,'content-type':invalid.contentType},payload:invalid.payload});assert.equal(response.statusCode,400,response.body)}
  const valid=await multipart(fields);const response=await app.inject({method:'POST',url:'/api/bug-report',headers:{...headers,'content-type':valid.contentType},payload:valid.payload});assert.equal(response.statusCode,200,response.body);assert.equal(delivered,1);
});
