import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {buildServer} from '../backend/src/server.js';

async function fixture(){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'musikbot-resource-reset-')),metricsProvider=async()=>({time:new Date().toISOString(),cpu:{busyPercent:25,cores:2},memory:{used:256*1024*1024,total:2*1024*1024*1024,free:1792*1024*1024},network:{rxPerSecond:20_000,txPerSecond:8_000,rxTotal:100_000,txTotal:40_000},load:[.1,.2,.3],uptime:3600,disk:null}),app=await buildServer({dataDir:dir,musicDir:path.join(dir,'music'),stateFile:path.join(dir,'state.json'),secretFile:path.join(dir,'secret.key'),frontendDir:path.resolve('frontend'),setupToken:'setup-test-token',logger:false,metricsProvider});return {dir,app}}
async function setup(app){const response=await app.inject({method:'POST',url:'/api/setup',headers:{'x-musikbot-setup-token':'setup-test-token'},payload:{username:'admin',password:'correct-horse-battery'}});return response.json().token}

test('resource measurement reset endpoint clears only the system test state',async t=>{const {dir,app}=await fixture();t.after(async()=>{await app.close();await fs.rm(dir,{recursive:true,force:true})});const token=await setup(app),headers={authorization:`Bearer ${token}`},stateFile=path.join(dir,'state.json'),before=JSON.parse(await fs.readFile(stateFile,'utf8')),protectedState={networkHistory:structuredClone(before.networkHistory),networkTracker:structuredClone(before.networkTracker),listeningProfile:structuredClone(before.listeningProfile),playbackResume:structuredClone(before.playbackResume)};let response=await app.inject({method:'POST',url:'/api/monitoring/advisor/reset',headers});assert.equal(response.statusCode,200,response.body);assert.equal(response.json().samples,0);assert.equal(response.json().progressPercent,0);const saved=JSON.parse(await fs.readFile(stateFile,'utf8'));assert.deepEqual(saved.resourceHistory,[]);assert.deepEqual(saved.resourceMeasurement,{version:1,startedAt:null,completedAt:null});assert.deepEqual(saved.networkHistory,protectedState.networkHistory);assert.deepEqual(saved.networkTracker,protectedState.networkTracker);assert.deepEqual(saved.listeningProfile,protectedState.listeningProfile);assert.deepEqual(saved.playbackResume,protectedState.playbackResume);response=await app.inject({url:'/api/monitoring/advisor',headers});assert.equal(response.statusCode,200);assert.equal(response.json().samples,0)});
