import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import http from "node:http";
import { once } from "node:events";
const require = createRequire(import.meta.url);
const { chromium } = require("../backend/node_modules/playwright");
import { systemInfo, networkInfo, storageInfo, calculateCpuPercent, selectNetworkInterfaces } from "../backend/src/system.js";
