import path from "node:path";
export const ROOT=process.env.RADIOBOT_DATA||"/var/lib/radiobot";
export const PORT=Number(process.env.PORT||3000);
export const HOST=process.env.HOST||"0.0.0.0";
export const FRONTEND=path.resolve(process.env.RADIOBOT_FRONTEND||path.join(process.cwd(),"../frontend"));
export const YTDLP=process.env.YTDLP_PATH||"yt-dlp";
export const FFMPEG=process.env.FFMPEG_PATH||"ffmpeg";
export const SPOTIFY_ID=process.env.SPOTIFY_CLIENT_ID||"";
export const SPOTIFY_SECRET=process.env.SPOTIFY_CLIENT_SECRET||"";
export const DISCORD_TOKEN=process.env.DISCORD_TOKEN||"";
export const dataFile=(name:string)=>path.join(ROOT,name);