import { Client, GatewayIntentBits, REST, Routes } from 'discord.js';
import { createAudioPlayer, createAudioResource, joinVoiceChannel, NoSubscriberBehavior, StreamType } from '@discordjs/voice';
import { PassThrough } from 'node:stream';

export class DiscordManager{
  constructor(store,player){this.store=store;this.player=player;this.instances=new Map()}
  async connect(cfg){if(this.instances.has(cfg.id))await this.disconnect(cfg.id);const intents=[GatewayIntentBits.Guilds,GatewayIntentBits.GuildVoiceStates];if(cfg.messageContent)intents.push(GatewayIntentBits.MessageContent);const client=new Client({intents});const pcm=new PassThrough({highWaterMark:1024*1024});const audio=createAudioPlayer({behaviors:{noSubscriber:NoSubscriberBehavior.Pause}});audio.play(createAudioResource(pcm,{inputType:StreamType.Raw}));let connection=null;client.once('ready',async()=>{const guild=await client.guilds.fetch(cfg.guildId);const vc=await guild.channels.fetch(cfg.voiceChannelId);connection=joinVoiceChannel({channelId:vc.id,guildId:guild.id,adapterCreator:guild.guild.voiceAdapterCreator,selfDeaf:false});connection.subscribe(audio)});client.on('error',e=>console.error('Discord:',e));client.on('interactionCreate',async i=>{if(!i.isChatInputCommand())return;try{switch(i.commandName){case'play':await this.player.enqueue({source:'youtube',url:i.options.getString('query',true),title:i.options.getString('query',true)});break;case'pause':this.player.pause();break;case'resume':this.player.resume();break;case'skip':await this.player.skip();break;case'stop':this.player.stop();break;case'clear':this.player.clear();break;case'volume':this.player.setVolume(i.options.getInteger('percent',true));break;case'queue':await i.reply({content:this.player.list().slice(0,20).map((x,n)=>`${n+1}. ${x.title||x.url}`).join('\n')||'Queue leer',ephemeral:true});return;case'nowplaying':await i.reply({content:this.player.now()?.title||'Nichts läuft',ephemeral:true});return;case'help':await i.reply({content:'/play /pause /resume /skip /stop /clear /volume /queue /nowplaying',ephemeral:true});return}await i.reply({content:'OK',ephemeral:true})}catch(e){await i.reply({content:e.message,ephemeral:true}).catch(()=>{})}});await client.login(cfg.token);await new REST({version:'10'}).setToken(cfg.token).put(Routes.applicationGuildCommands(client.user.id,cfg.guildId),{body:[{name:'play',description:'Titel oder URL abspielen',options:[{name:'query',description:'Titel oder URL',type:3,required:true}]},{name:'pause',description:'Pausieren'},{name:'resume',description:'Fortsetzen'},{name:'skip',description:'Überspringen'},{name:'stop',description:'Stoppen'},{name:'clear',description:'Queue leeren'},{name:'volume',description:'Lautstärke',options:[{name:'percent',description:'0-100',type:4,required:true,min_value:0,max_value:100}]},{name:'queue',description:'Queue anzeigen'},{name:'nowplaying',description:'Aktuellen Titel anzeigen'},{name:'help',description:'Hilfe'}]});const output={write(buf){pcm.write(buf)},close(){try{pcm.end()}catch{}},disconnect(){try{connection?.destroy()}catch{}try{client.destroy()}catch{}}};this.instances.set(cfg.id,output);this.player.addOutput(output);return true}
  async disconnect(id){const o=this.instances.get(id);if(!o)return;o.disconnect();this.player.removeOutput(o);this.instances.delete(id)}
}
