import {ChannelType,Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder} from 'discord.js';
import {AudioPlayer,StreamType,createAudioPlayer,createAudioResource,joinVoiceChannel} from '@discordjs/voice';
import {PassThrough} from 'node:stream';
export class DiscordManager{
 constructor(music){this.music=music;this.map=new Map();}
 async handleSlash(i){switch(i.commandName){case'play':{const q=i.options.getString('suche',true);await this.music.enqueue([{id:crypto.randomUUID(),title:q,url:q,source:'youtube'}]);return i.reply(`▶️ **${q}** hinzugefügt.`);}case'pause':this.music.pause();return i.reply('⏸️ Pausiert.');case'resume':this.music.resume();return i.reply('▶️ Fortgesetzt.');case'skip':this.music.skip();return i.reply('⏭️ Übersprungen.');case'stop':this.music.stop();return i.reply('⏹️ Gestoppt.');case'volume':{const v=i.options.getInteger('wert',true);this.music.setVolume(v);return i.reply(`🔊 Lautstärke: **${v}%**`);}case'queue':return i.reply(this.music.queue.map(x=>x.title).join('\n')||'Queue ist leer.');}}
 commandData(){return[new SlashCommandBuilder().setName('play').setDescription('Musik abspielen').addStringOption(o=>o.setName('suche').setDescription('Titel, Interpret oder URL').setRequired(true)),new SlashCommandBuilder().setName('pause').setDescription('Wiedergabe pausieren'),new SlashCommandBuilder().setName('resume').setDescription('Wiedergabe fortsetzen'),new SlashCommandBuilder().setName('skip').setDescription('Titel überspringen'),new SlashCommandBuilder().setName('stop').setDescription('Wiedergabe stoppen'),new SlashCommandBuilder().setName('volume').setDescription('Lautstärke').addIntegerOption(o=>o.setName('wert').setDescription('0 bis 100').setMinValue(0).setMaxValue(100).setRequired(true)),new SlashCommandBuilder().setName('queue').setDescription('Warteschlange anzeigen')].map(x=>x.toJSON());}
 async connect(cfg){await this.disconnect(cfg.id);if(!cfg.enabled)throw new Error('Instanz ist ausgeschaltet');if(!cfg.token)throw new Error('Bot-Token fehlt');const r={cfg,client:new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildVoiceStates,GatewayIntentBits.MessageContent]})};r.client.on('interactionCreate',async i=>{if(!i.isChatInputCommand())return;try{await this.handleSlash(i);}catch(e){const m=e instanceof Error?e.message:String(e);if(i.replied||i.deferred)await i.followUp({content:`Fehler: ${m}`,ephemeral:true});else await i.reply({content:`Fehler: ${m}`,ephemeral:true});}});r.client.on('messageCreate',async m=>{if(m.author.bot||!m.guild||!m.content.startsWith(cfg.prefix))return;const [c,...a]=m.content.slice(cfg.prefix.length).trim().split(/\s+/);try{if(c==='play')await this.music.enqueue([{id:crypto.randomUUID(),title:a.join(' '),url:a.join(' '),source:'youtube'}]);else if(c==='pause')this.music.pause();else if(c==='resume')this.music.resume();else if(c==='skip')this.music.skip();else if(c==='stop')this.music.stop();else if(c==='volume')this.music.setVolume(Number(a[0]));else if(c==='queue')await m.reply(this.music.queue.map(x=>x.title).join('\n')||'Queue ist leer.');}catch(e){await m.reply(`Fehler: ${e instanceof Error?e.message:String(e)}`);}});try{await r.client.login(cfg.token);this.map.set(cfg.id,r);if(r.client.user){const rest=new REST({version:'10'}).setToken(cfg.token);void rest.put(Routes.applicationCommands(r.client.user.id),{body:this.commandData()}).catch(err=>console.error('Discord command registration failed',err));}}catch(e){try{await r.client.destroy();}catch{}throw e;}}
 async disconnect(id){const r=this.map.get(id);if(!r)return;try{r.voice?.destroy();r.stream?.end();await r.client.destroy();}finally{this.map.delete(id);}}
 async join(id){const r=this.map.get(id);if(!r)throw new Error('Discord-Instanz nicht verbunden');if(!r.cfg.guildId||!r.cfg.channelId)throw new Error('Server und Voice-Kanal auswählen');const g=r.client.guilds.cache.get(r.cfg.guildId);if(!g)throw new Error('Discord-Server nicht gefunden');const ch=g.channels.cache.get(r.cfg.channelId);if(!ch||ch.type!==ChannelType.GuildVoice)throw new Error('Voice-Kanal nicht gefunden');r.voice=joinVoiceChannel({guildId:g.id,channelId:ch.id,adapterCreator:g.voiceAdapterCreator});r.player=createAudioPlayer();r.voice.subscribe(r.player);r.stream=new PassThrough();r.player.play(createAudioResource(r.stream,{inputType:StreamType.Raw}));}
 writeAudio(data,id){this.map.get(id)?.stream?.write(data);}
 guilds(id){const r=this.map.get(id);return r?[...r.client.guilds.cache.values()].map(g=>({id:g.id,name:g.name})):[];}
 channels(id,guildId){const g=this.map.get(id)?.client.guilds.cache.get(guildId);return g?[...g.channels.cache.values()].filter(c=>c.type===ChannelType.GuildVoice).map(c=>({id:c.id,name:c.name})):[];}
 status(){return[...this.map.values()].map(r=>({id:r.cfg.id,name:r.cfg.name,enabled:r.cfg.enabled,connected:true,guildId:r.cfg.guildId,channelId:r.cfg.channelId,inviteUrl:r.cfg.clientId?`https://discord.com/oauth2/authorize?client_id=${encodeURIComponent(r.cfg.clientId)}&scope=bot%20applications.commands&permissions=36700160`:''}));}
}
