import Fastify from "fastify";
import cors from "@fastify/cors";
import fastifyStatic from "@fastify/static";
import {FRONTEND,HOST,PORT} from "./config.js";
import {load,db,save,ensureAdmin,login,auth} from "./store.js";
import {youtubeSearch,radioSearch} from "./media.js";
import {spotifySearch} from "./spotify.js";
import {system,interfaces} from "./system.js";
import {network} from "./network.js";
import {DiscordManager} from "./discord.js";
import {TS3Manager} from "./ts3.js";
import {Player} from "./playback.js";
const app=Fastify({logger:true});const discord=new DiscordManager(),ts3=new TS3Manager(),player=new Player();
await load();await app.register(cors,{origin:true});await app.register(fastifyStatic,{root:FRONTEND,prefix:"/"});
const ok=(req:any)=>auth(req.headers.authorization?.replace(/^Bearer /,""));
app.get("/api/setup",()=>({initialized:db().users.length>0}));
app.post("/api/setup",async(req:any,rep)=>{if(db().users.length)return rep.code(409).send({error:"already initialized"});const {name,password}=req.body||{};if(!name||!password||password.length<10)return rep.code(400).send({error:"Benutzername und Passwort (min. 10 Zeichen) erforderlich"});await ensureAdmin(name,password);return login(name,password)});
app.post("/api/login",(req:any,rep)=>{const x=login(req.body?.name||"",req.body?.password||"");return x||rep.code(401).send({error:"Ungültige Anmeldung"})});
app.get("/api/me",(req:any,rep)=>{const u=ok(req);return u?{id:u.id,name:u.name,role:u.role}:rep.code(401).send({error:"unauthorized"})});
app.addHook("preHandler",async(req:any,rep)=>{if(req.url.startsWith("/api/setup")||req.url.startsWith("/api/login")||req.url==="/api/health")return;if(req.url.startsWith("/api/")&&!ok(req))return rep.code(401).send({error:"unauthorized"})});
app.get("/api/health",()=>({ok:true}));
app.get("/api/search",async(req:any)=>{const q=String((req.query as any).q||"").trim();if(!q)return {youtube:[],radio:[],spotify:[]};const source=String((req.query as any).source||"all");const out:any={youtube:[],radio:[],spotify:[]};await Promise.allSettled([source==="all"||source==="youtube"?youtubeSearch(q).then(x=>out.youtube=x):Promise.resolve(),source==="all"||source==="radio"?radioSearch(q).then(x=>out.radio=x):Promise.resolve(),source==="all"||source==="spotify"?spotifySearch(q).then(x=>out.spotify=x):Promise.resolve()]);return out});
app.get("/api/system",()=>system());app.get("/api/interfaces",()=>interfaces());app.get("/api/network",()=>network());
app.get("/api/state",()=>({...player.snapshot(),dashboard:db().dashboard,settings:db().settings,discord:db().discord,ts3:ts3.status(),activeInstance:db().settings.activeInstance}));
app.post("/api/play",async(req:any)=>{await player.enqueue(req.body?.items||[]);return player.snapshot()});
app.post("/api/play/:action",async(req:any)=>{const a=req.params.action;if(a==="pause")player.pause();else if(a==="resume")player.resume();else if(a==="stop")player.stop();else if(a==="skip")player.skip();else if(a==="volume")player.setVolume(Number(req.body?.value));return player.snapshot()});
app.get("/api/playlists",()=>db().playlists);
app.post("/api/playlists",async(req:any)=>{const p={id:crypto.randomUUID(),name:String(req.body?.name||"Neue Playlist"),items:[]};db().playlists.push(p);await save();return p});
app.post("/api/playlists/:id/items",async(req:any)=>{const p=db().playlists.find(x=>x.id===req.params.id);if(!p)return {error:"not found"};p.items.push(...(req.body?.items||[]));await save();return p});
app.post("/api/playlists/:id/play",async(req:any)=>{const p=db().playlists.find(x=>x.id===req.params.id);if(p)await player.enqueue(p.items);return player.snapshot()});
app.delete("/api/playlists/:id/items/:itemId",async(req:any)=>{const p=db().playlists.find(x=>x.id===req.params.id);if(p)p.items=p.items.filter(x=>x.id!==req.params.itemId);await save();return p});
app.get("/api/dashboard",()=>({tiles:db().dashboard}));app.put("/api/dashboard",async(req:any)=>{db().dashboard=req.body?.tiles||db().dashboard;await save();return {tiles:db().dashboard}});
app.get("/api/users",()=>db().users.map(u=>({id:u.id,name:u.name,role:u.role})));
app.post("/api/users",async(req:any)=>{const {name,password,role}=req.body||{};if(db().users.some(u=>u.name===name))return {error:"exists"};const {scryptSync}=await import("node:crypto");db().users.push({id:crypto.randomUUID(),name,passwordHash:scryptSync(password,"radiobot",32).toString("hex"),role:role==="user"?"user":"admin"});await save();return {name,role}});
app.get("/api/discord/status",()=>discord.status());app.post("/api/discord/connect",async(req:any)=>discord.connect(req.body?.token));app.post("/api/discord/disconnect",async()=>{await discord.disconnect();return discord.status()});app.post("/api/discord/join",async(req:any)=>discord.join(req.body.guildId,req.body.channelId));app.get("/api/discord/guilds",()=>discord.guilds());app.get("/api/discord/guilds/:id/channels",(req:any)=>discord.channels(req.params.id));
app.get("/api/ts3",()=>ts3.status());app.put("/api/ts3",async(req:any)=>{ts3.set(req.body?.instances||[]);db().ts3=ts3.configs;await save();return ts3.status()});app.post("/api/ts3/:id/connect",(req:any)=>ts3.connect(req.params.id));app.post("/api/ts3/:id/disconnect",async(req:any)=>{await ts3.disconnect(req.params.id);return ts3.status()});
player.on("audio",(data:Buffer)=>{discord.attachAudio(data);void ts3.sendVoice(data)});
app.get("/",async(_,rep)=>rep.sendFile("index.html"));
await app.listen({port:PORT,host:HOST});