import Fastify from "fastify";
import cors from "@fastify/cors";
import statik from "@fastify/static";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { spawn, type ChildProcess } from "node:child_process";
import { PassThrough } from "node:stream";
import { randomUUID, scryptSync, timingSafeEqual } from "node:crypto";
import { Client, GatewayIntentBits, ChannelType } from "discord.js";
import { joinVoiceChannel, createAudioPlayer, createAudioResource, StreamType } from "@discordjs/voice";
import { Client as TSClient, generateIdentity } from "@honeybbq/teamspeak-client";
import OpusScript from "opusscript";

type Item={id:string;title:string;url:string;source:string;duration?:number;thumbnail?:string};
type User={id:string;name:string;hash:string;role:"admin"|"user"};
type Tile={id:string;title:string;color:string;icon:string;locked:boolean};
type State={users:User[];playlists:{id:string;name:string;items:Item[]}[];settings:Record<string,unknown>;dashboard:Tile[];discord:any[];ts3:any[]};
const ROOT=process.env.RADIOBOT_DATA||"/var/lib/radiobot",PORT=Number(process.env.PORT||3000),HOST=process.env.HOST||"0.0.0.0";
const FRONTEND=path.resolve(process.env.RADIOBOT_FRONTEND||path.join(process.cwd(),"../frontend")),YTDLP=process.env.YTDLP_PATH||"yt-dlp",FFMPEG=process.env.FFMPEG_PATH||"ffmpeg",DATA=path.join(ROOT,"state.json");
const defaults:State={users:[],playlists:[],settings:{volume:80,mode:"queue",activeInstance:"default",networkInterface:"auto",prefix:"!",discordBotClientId:""},dashboard:[
{id:"now",title:"Jetzt läuft",color:"violet",icon:"🎵",locked:true},{id:"queue",title:"Queue",color:"blue",icon:"📋",locked:true},{id:"search",title:"Suche",color:"green",icon:"🔎",locked:true},{id:"radio",title:"Radio",color:"orange",icon:"📻",locked:true},{id:"system",title:"System",color:"pink",icon:"🖥️",locked:true},{id:"network",title:"Netzwerk",color:"cyan",icon:"🌐",locked:true},{id:"instances",title:"Instanzen",color:"indigo",icon:"🎧",locked:true},{id:"playlists",title:"Playlists",color:"amber",icon:"💿",locked:true}],discord:[],ts3:[]};
let state:State=structuredClone(defaults);const sessions=new Map<string,string>();let saveTimer:ReturnType<typeof setTimeout>|undefined;
async function save(){if(saveTimer)clearTimeout(saveTimer);saveTimer=setTimeout(()=>void writeFile(DATA,JSON.stringify(state,null,2),"utf8"),50)}
async function load(){await mkdir(ROOT,{recursive:true});try{state=JSON.parse(await readFile(DATA,"utf8")) as State}catch{await writeFile(DATA,JSON.stringify(state,null,2),"utf8")}}
function hash(p:string){return scryptSync(p,"radiobot-v4",32).toString("hex")}
function auth(req:any){const t=String(req.headers.authorization||"").replace(/^Bearer /,"");const id=sessions.get(t);return state.users.find(u=>u.id===id)}
async function json(url:string,init?:RequestInit){const r=await fetch(url,init);if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
function yt(q:string):Promise<Item[]>{return new Promise((resolve,reject)=>{const p=spawn(YTDLP,[`ytsearch8:${q}`,"--flat-playlist","--dump-single-json","--no-warnings"]);let s="";p.stdout.on("data",d=>s+=d.toString());p.on("error",reject);p.on("close",c=>{if(c)return reject(new Error("yt-dlp search failed"));try{const j=JSON.parse(s);resolve((j.entries||[]).map((x:any)=>({id:x.id||randomUUID(),title:x.title,url:x.url||`https://www.youtube.com/watch?v=${x.id}`,duration:x.duration,source:"youtube",thumbnail:x.thumbnails?.[0]?.url})))}catch(e){reject(e)}})})}
async function radio(q:string):Promise<Item[]>{const j=await json("https://de1.api.radio-browser.info/json/stations/search?limit=15&hidebroken=true&order=clickcount&reverse=true&name="+encodeURIComponent(q));return j.map((x:any)=>({id:x.stationuuid,title:x.name,url:x.url_resolved||x.url,source:"radio",thumbnail:x.favicon}))}
let spToken="",spExpiry=0;async function spotify(q:string):Promise<Item[]>{const id=process.env.SPOTIFY_CLIENT_ID,secret=process.env.SPOTIFY_CLIENT_SECRET;if(!id||!secret)return[];if(Date.now()>=spExpiry){const basic=Buffer.from(`${id}:${secret}`).toString("base64");const t=await json("https://accounts.spotify.com/api/token",{method:"POST",headers:{Authorization:`Basic ${basic}`,"Content-Type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials"});spToken=t.access_token;spExpiry=Date.now()+((t.expires_in||3600)-60)*1000}const j=await json("https://api.spotify.com/v1/search?type=track&limit=8&q="+encodeURIComponent(q),{headers:{Authorization:`Bearer ${spToken}`}});return(j.tracks?.items||[]).map((x:any)=>({id:x.id,title:`${x.name} — ${(x.artists||[]).map((a:any)=>a.name).join(", ")}`,url:x.external_urls?.spotify||"",source:"spotify",duration:x.duration_ms/1000,thumbnail:x.album?.images?.[0]?.url}))}
async function streamUrl(x:Item):Promise<string>{if(x.source==="radio")return x.url;if(x.source==="spotify"){const y=(await yt(x.title))[0];if(!y)throw new Error("Kein Medium gefunden");return streamUrl(y)}return new Promise((resolve,reject)=>{const p=spawn(YTDLP,[x.url,"-g","-f","bestaudio/best","--no-playlist","--no-warnings"]);let s="";p.stdout.on("data",d=>s+=d.toString());p.on("error",reject);p.on("close",c=>{const u=s.trim().split(/\r?\n/)[0];if(c||!u)return reject(new Error("stream resolve failed"));resolve(u)})})}
class Player{queue:Item[]=[];current:Item|null=null;paused=false;volume=80;mode:"queue"|"repeat"|"shuffle"="queue";ffmpeg:ChildProcess|undefined;listeners=new Set<(b:Buffer)=>void>();async enqueue(xs:Item[]){this.queue.push(...xs);if(!this.current)await this.next()}async next(){this.stopProc();this.current=this.mode==="shuffle"&&this.queue.length>1?this.queue.splice(Math.floor(Math.random()*this.queue.length),1)[0]||null:this.queue.shift()||null;this.paused=false;if(!this.current)return;try{const u=await streamUrl(this.current);const p=spawn(FFMPEG,["-hide_banner","-loglevel","error","-reconnect","1","-reconnect_streamed","1","-reconnect_delay_max","5","-i",u,"-vn","-f","s16le","-ar","48000","-ac","2","pipe:1"]);this.ffmpeg=p;p.stdout?.on("data",d=>this.listeners.forEach(fn=>fn(Buffer.from(d))));p.on("close",()=>{if(this.current&&!this.paused)void this.next()})}catch{this.current=null;await this.next()}}pause(){this.ffmpeg?.kill("SIGSTOP");if(this.ffmpeg)this.paused=true}resume(){this.ffmpeg?.kill("SIGCONT");if(this.ffmpeg)this.paused=false}stop(){this.stopProc();this.current=null;this.paused=false}skip(){this.stopProc();void this.next()}setVolume(v:number){this.volume=Math.max(0,Math.min(100,v))}stopProc(){this.ffmpeg?.kill("SIGTERM");this.ffmpeg=undefined}snapshot(){return{current:this.current,queue:this.queue,paused:this.paused,volume:this.volume,mode:this.mode}}}
class DiscordOut{instances=new Map<string,any>();async connect(c:any){const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildVoiceStates]});await client.login(c.token);this.instances.set(c.id,{...c,client,voice:undefined,player:undefined,stream:undefined});return this.status()}async disconnect(id:string){const x=this.instances.get(id);if(!x)return;x.voice?.destroy();x.stream?.end();await x.client.destroy();this.instances.delete(id)}async join(id:string){const x=this.instances.get(id);if(!x)throw new Error("Discord-Instanz nicht verbunden");const g=x.client.guilds.cache.get(x.guildId);if(!g)throw new Error("Guild nicht gefunden");x.voice=joinVoiceChannel({guildId:g.id,channelId:x.channelId,adapterCreator:g.voiceAdapterCreator});x.player=createAudioPlayer();x.voice.subscribe(x.player);x.stream=new PassThrough();x.player.play(createAudioResource(x.stream,{inputType:StreamType.Raw}))}audio(b:Buffer){for(const x of this.instances.values())x.stream?.write(b)}status(){return[...this.instances.values()].map(x=>({id:x.id,name:x.name,connected:true,guildId:x.guildId||"",channelId:x.channelId||"",guilds:x.client.guilds.cache.size,prefix:x.prefix||"!"}))}guilds(id:string){const x=this.instances.get(id);return x?[...x.client.guilds.cache.values()].map((g:any)=>({id:g.id,name:g.name})):[]}channels(id:string,gid:string){const x=this.instances.get(id),g=x?.client.guilds.cache.get(gid);return g?[...g.channels.cache.values()].filter((c:any)=>c.type===ChannelType.GuildVoice).map((c:any)=>({id:c.id,name:c.name})):[]}}
class TSOut{configs:any[]=[];clients=new Map<string,any>();encoder=new OpusScript(48000,2,OpusScript.Application.AUDIO);pcm=Buffer.alloc(0);set(c:any[]){this.configs=c}async connect(id:string){const c=this.configs.find(x=>x.id===id);if(!c)throw new Error("TS3-Instanz nicht gefunden");const cl=new TSClient(generateIdentity(8),c.host,c.nickname,{serverPassword:c.password,defaultChannel:c.channel});await cl.connect();await cl.waitConnected(AbortSignal.timeout(15000));this.clients.set(id,cl);return this.status()}async disconnect(id:string){const c=this.clients.get(id);if(c){await c.disconnect();this.clients.delete(id)}}audio(b:Buffer){if(!this.clients.size)return;this.pcm=Buffer.concat([this.pcm,b]);while(this.pcm.length>=3840){const f=this.pcm.subarray(0,3840);this.pcm=this.pcm.subarray(3840);const o=this.encoder.encode(f,960);for(const c of this.clients.values())c.sendVoice(o,4)}}status(){return this.configs.map(c=>({...c,password:undefined,connected:this.clients.has(c.id)}))}}
function system(){const total=os.totalmem(),free=os.freemem();return{hostname:os.hostname(),platform:process.platform,node:process.version,cores:os.cpus().length,load:os.loadavg(),ram:{total,used:total-free,free},uptime:os.uptime()}}
async function network(){const out:any[]=[];for(const [name,vals] of Object.entries(os.networkInterfaces())){const rx=await readFile(`/sys/class/net/${name}/statistics/rx_bytes`,"utf8").catch(()=>"0"),tx=await readFile(`/sys/class/net/${name}/statistics/tx_bytes`,"utf8").catch(()=>"0");out.push({name,rx:Number(rx),tx:Number(tx),addresses:(vals||[]).map(v=>v.address)})}return{interfaces:out,selected:state.settings.networkInterface}}
const player=new Player(),discord=new DiscordOut(),ts3=new TSOut(),app=Fastify({logger:true});player.listeners.add(b=>discord.audio(b));player.listeners.add(b=>ts3.audio(b));
await load();await app.register(cors,{origin:true});await app.register(statik,{root:FRONTEND,prefix:"/"});
app.get("/api/setup",()=>({initialized:state.users.length>0}));app.post("/api/setup",async(req:any,rep)=>{if(state.users.length)return rep.code(409).send({error:"already initialized"});const b=req.body||{};if(!b.name||String(b.password||"").length<10)return rep.code(400).send({error:"Benutzername und Passwort (min. 10 Zeichen) erforderlich"});state.users.push({id:randomUUID(),name:b.name,hash:hash(b.password),role:"admin"});const token=randomUUID();sessions.set(token,state.users[0].id);await save();return{token}});
app.post("/api/login",(req:any,rep)=>{const b=req.body||{},u=state.users.find(x=>x.name===b.name);if(!u)return rep.code(401).send({error:"Ungültige Anmeldung"});const a=Buffer.from(u.hash,"hex"),bb=Buffer.from(hash(String(b.password||"")),"hex");if(a.length!==bb.length||!timingSafeEqual(a,bb))return rep.code(401).send({error:"Ungültige Anmeldung"});const token=randomUUID();sessions.set(token,u.id);return{token,user:{id:u.id,name:u.name,role:u.role}}});
app.addHook("preHandler",async(req:any,rep)=>{if(req.url.startsWith("/api/setup")||req.url.startsWith("/api/login")||req.url==="/api/health")return;if(req.url.startsWith("/api/")&&!auth(req))return rep.code(401).send({error:"unauthorized"})});
app.get("/api/health",()=>({ok:true,version:"4.0.1"}));app.get("/api/state",()=>({...player.snapshot(),dashboard:state.dashboard,settings:state.settings,discord:discord.status(),ts3:ts3.status()}));app.post("/api/play",async(req:any)=>{await player.enqueue((req.body?.items||[]).map((x:any)=>({...x,id:x.id||randomUUID()})));return player.snapshot()});
app.post("/api/play/:action",async(req:any)=>{const a=(req.params as {action:string}).action;if(a==="pause")player.pause();else if(a==="resume")player.resume();else if(a==="stop")player.stop();else if(a==="skip")player.skip();else if(a==="volume")player.setVolume(Number(req.body?.value));return player.snapshot()});
app.get("/api/search",async(req:any)=>{const q=String((req.query as any)?.q||"").trim();if(!q)return{youtube:[],radio:[],spotify:[]};const source=String((req.query as any)?.source||"all"),out:any={youtube:[],radio:[],spotify:[]};await Promise.allSettled([source==="all"||source==="youtube"?yt(q).then(x=>out.youtube=x):Promise.resolve(),source==="all"||source==="radio"?radio(q).then(x=>out.radio=x):Promise.resolve(),source==="all"||source==="spotify"?spotify(q).then(x=>out.spotify=x):Promise.resolve()]);return out});
app.get("/api/playlists",()=>state.playlists);app.post("/api/playlists",async(req:any)=>{const p={id:randomUUID(),name:String(req.body?.name||"Neue Playlist"),items:[] as Item[]};state.playlists.push(p);await save();return p});app.post("/api/playlists/:id/items",async(req:any)=>{const p=state.playlists.find(x=>x.id===(req.params as {id:string}).id);if(!p)return{error:"not found"};p.items.push(...(req.body?.items||[]));await save();return p});app.post("/api/playlists/:id/play",async(req:any)=>{const p=state.playlists.find(x=>x.id===(req.params as {id:string}).id);if(p)await player.enqueue(p.items);return player.snapshot()});app.delete("/api/playlists/:id/items/:itemId",async(req:any)=>{const p=req.params as {id:string;itemId:string},pl=state.playlists.find(x=>x.id===p.id);if(pl)pl.items=pl.items.filter(x=>x.id!==p.itemId);await save();return pl});
app.get("/api/dashboard",()=>({tiles:state.dashboard}));app.put("/api/dashboard",async(req:any)=>{const ids=(req.body?.tiles||[]).map(String);const ordered=ids.map((id:string)=>state.dashboard.find(t=>t.id===id)).filter(Boolean) as Tile[];const missing=state.dashboard.filter(t=>!ids.includes(t.id));state.dashboard=[...ordered,...missing];await save();return{tiles:state.dashboard}});app.put("/api/settings",async(req:any)=>{state.settings={...state.settings,...(req.body||{})};await save();return state.settings});app.get("/api/system",system);app.get("/api/network",network);
app.get("/api/discord/status",()=>discord.status());app.post("/api/discord/instances",async(req:any)=>{state.discord.push(req.body);await save();return state.discord});app.post("/api/discord/connect",async(req:any)=>discord.connect(req.body));app.post("/api/discord/:id/join",async(req:any)=>{await discord.join((req.params as {id:string}).id);return discord.status()});app.get("/api/discord/:id/guilds",req=>discord.guilds((req.params as {id:string}).id));app.get("/api/discord/:id/guilds/:gid/channels",req=>{const p=req.params as {id:string;gid:string};return discord.channels(p.id,p.gid)});app.post("/api/discord/:id/disconnect",async(req:any)=>{await discord.disconnect((req.params as {id:string}).id);return discord.status()});
app.get("/api/ts3",()=>ts3.status());app.put("/api/ts3",async(req:any)=>{ts3.set(req.body?.instances||[]);state.ts3=ts3.configs;await save();return ts3.status()});app.post("/api/ts3/:id/connect",req=>ts3.connect((req.params as {id:string}).id));app.post("/api/ts3/:id/disconnect",async req=>{await ts3.disconnect((req.params as {id:string}).id);return ts3.status()});
app.get("/",(_,rep)=>rep.sendFile("index.html"));
await app.listen({port:PORT,host:HOST});
