import {EventEmitter} from 'node:events';
const commandNames=['play','pause','resume','skip','stop','clear','volume','queue','nowplaying','help'];
export class IntegrationManager extends EventEmitter{
  constructor({player,store,secrets}){super();this.player=player;this.store=store;this.secrets=secrets;this.runtimes=new Map();player.on('pcm',b=>{const {output,outputId}=store.data.settings;if(output==='none'||!outputId)return;const runtime=this.runtimes.get(outputId);if(runtime?.type===output)runtime.write?.(b);});}
  status(){return [...this.runtimes.entries()].map(([id,r])=>({id,type:r.type,status:r.status||'offline',detail:r.detail||''}));}
  async connect(connection){await this.disconnect(connection.id,true);if(connection.type==='discord')return this.connectDiscord(connection);if(connection.type==='ts3')return this.connectTs3(connection);throw new Error('Unbekannter Verbindungstyp');}
  async connectDiscord(c){const {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder}=await import('discord.js');const {joinVoiceChannel,createAudioPlayer,createAudioResource,StreamType}=await import('@discordjs/voice');const {PassThrough}=await import('node:stream');const token=this.secrets.open(c.secret);if(!token)throw new Error('Bot-Token fehlt');const intents=[GatewayIntentBits.Guilds,GatewayIntentBits.GuildVoiceStates];if(c.messageContent)intents.push(GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent);const client=new Client({intents});const stream=new PassThrough({highWaterMark:1024*1024});const audio=createAudioPlayer();audio.play(createAudioResource(stream,{inputType:StreamType.Raw}));const runtime={type:'discord',status:'connecting',manual:false,client,write:b=>stream.write(b),close:async()=>{runtime.manual=true;stream.destroy();audio.stop();client.destroy();}};this.runtimes.set(c.id,runtime);
    client.on('ready',()=>{(async()=>{runtime.status='online';runtime.detail=client.user.tag;const guild=client.guilds.cache.get(c.guildId);if(!guild)throw new Error('Konfigurierte Guild nicht gefunden');const voice=guild.channels.cache.get(c.voiceChannelId);if(voice){const vc=joinVoiceChannel({channelId:voice.id,guildId:guild.id,adapterCreator:guild.voiceAdapterCreator,selfDeaf:true});vc.subscribe(audio);runtime.voice=vc;}const commands=commandNames.map(name=>new SlashCommandBuilder().setName(name).setDescription(`MusikBot187: ${name}`));commands[0].addStringOption(o=>o.setName('query').setDescription('Titel, Interpret oder URL').setRequired(true));commands[6].addIntegerOption(o=>o.setName('value').setDescription('0–100').setRequired(true).setMinValue(0).setMaxValue(100));await new REST({version:'10'}).setToken(token).put(Routes.applicationGuildCommands(c.clientId,c.guildId),{body:commands.map(x=>x.toJSON())});})().catch(async error=>{runtime.status='error';runtime.detail=error.message;await this.store.diagnostic('error','discord',`${c.name}: ${error.message}`);});});
    client.on('interactionCreate',i=>{if(!i.isChatInputCommand())return;if(i.guildId!==c.guildId)return i.reply({content:'Dieser Bot-Befehl ist für diesen Discord-Server nicht freigeschaltet.',ephemeral:true});this.handleCommand(i.commandName,i.options.getString('query'),i.options.getInteger('value')).then(x=>i.reply(String(x).slice(0,1900))).catch(e=>i.reply({content:e.message,ephemeral:true}));});
    client.on('messageCreate',m=>{if(!c.messageContent||!c.prefix||m.author.bot||m.guildId!==c.guildId||!m.content.startsWith(c.prefix))return;const [name,...rest]=m.content.slice(c.prefix.length).trim().split(/\s+/);if(commandNames.includes(name))this.handleCommand(name,rest.join(' '),Number(rest[0])).then(x=>m.reply(String(x))).catch(e=>m.reply(e.message));});
    client.on('error',e=>this.store.diagnostic('error','discord',e.message));await client.login(token);return runtime;}
  async handleCommand(name,query,value){if(name==='play'){const {youtubeSearch}=await import('./media.js');const [item]=await youtubeSearch(query);if(!item)throw new Error('Kein Treffer');this.player.add(item);return `Hinzugefügt: ${item.title}`;}if(name==='pause')this.player.pause();if(name==='resume')this.player.resume();if(name==='skip')this.player.skip();if(name==='stop')this.player.stop();if(name==='clear')this.player.clear();if(name==='volume')this.player.setVolume(value);if(name==='queue')return this.player.queue.map((x,i)=>`${i+1}. ${x.title}`).join('\n')||'Queue ist leer.';if(name==='nowplaying')return this.player.current?.title||'Nichts läuft.';if(name==='help')return commandNames.map(x=>`/${x}`).join(' · ');return 'OK';}
  discordOptions(id){const client=this.runtimes.get(id)?.client;if(!client?.isReady())return {guilds:[],voiceChannels:[]};const guilds=client.guilds.cache.map(g=>({id:g.id,name:g.name}));const voiceChannels=client.guilds.cache.flatMap(g=>g.channels.cache.filter(ch=>ch.isVoiceBased()).map(ch=>({id:ch.id,name:ch.name,guildId:g.id,guildName:g.name})));return {guilds,voiceChannels};}
  async connectTs3(c){const {TeamSpeak}=await import('ts3-nodejs-library');const password=this.secrets.open(c.secret);const client=await TeamSpeak.connect({host:c.host,queryport:Number(c.port||10011),serverport:Number(c.serverPort||9987),username:c.username||'serveradmin',password,nickname:c.nickname||'MusikBot187'});const runtime={type:'ts3',status:'online',detail:'ServerQuery verbunden',write:()=>{},close:()=>client.quit()};client.on('error',e=>this.store.diagnostic('error','ts3',e.message));this.runtimes.set(c.id,runtime);return runtime;}
  async disconnect(id,remove=false){const r=this.runtimes.get(id);if(r)await r.close?.();this.runtimes.delete(id);if(remove)this.emit('status',this.status());}
  async close(){for(const id of [...this.runtimes.keys()])await this.disconnect(id);}
}
