import {EventEmitter} from 'node:events';
const commandNames=['play','pause','resume','skip','stop','clear','volume','queue','nowplaying','help'];
export const discordOpusBitrate=128_000;
export const discordPcmBufferBytes=384_000;
export function writeDiscordPcm(runtime,buffer){if(!runtime?.stream||runtime.stream.destroyed||runtime.backpressured)return false;runtime.backpressured=!runtime.stream.write(buffer);return !runtime.backpressured;}
export class IntegrationManager extends EventEmitter{
  constructor({player,store,secrets}){super();this.player=player;this.store=store;this.secrets=secrets;this.runtimes=new Map();player.on('pcm',payload=>{if(payload?.buffer&&payload?.playerId){for(const[runtimeId,runtime]of this.runtimes)if(this.resolvePlayerId(runtimeId)===payload.playerId)runtime.write?.(payload.buffer);return}const {output,outputId}=store.data.settings;if(output==='none'||!outputId)return;const runtime=this.runtimes.get(outputId);if(runtime?.type===output)runtime.write?.(payload)});if(player.stateFor)player.on('instance-state',(id,state)=>this.syncPlayback(state,id));else player.on('state',state=>this.syncPlayback(state));}
  resolvePlayerId(id){return this.player?.resolve?.(id)||String(id||'')}
  playerFor(id){return this.player.for?.(this.resolvePlayerId(id))||this.player}
  playerStateFor(id){return this.player.stateFor?.(this.resolvePlayerId(id))||this.player.state()}
  syncPlayback(state,targetPlayerId=null){for(const[runtimeId,runtime]of this.runtimes){if(runtime.type!=='discord'||targetPlayerId&&this.resolvePlayerId(runtimeId)!==targetPlayerId)continue;try{const settings=this.store?.data?.settings,selected=targetPlayerId?this.resolvePlayerId(runtimeId)===targetPlayerId:!settings||settings.output==='discord'&&settings.outputId===runtimeId,presence=selected&&state.current&&!state.paused?String(state.current.title||'MusikBot187').slice(0,128):'';if(runtime.lastPresence!==presence&&runtime.client?.user){runtime.client.user.setPresence({activities:presence?[{name:presence,type:runtime.ActivityType.Listening}]:[],status:runtime.status==='online'?'online':'idle'});runtime.lastPresence=presence;}if(!selected||!state.current){if(runtime.playbackId!=null||runtime.lastPaused!=null)runtime.reset?.();runtime.lastPaused=null;continue;}if(runtime.playbackId!==state.playbackId){runtime.prepare?.(state.playbackId);runtime.lastPaused=null;}if(runtime.lastPaused!==state.paused){if(state.paused)runtime.audio.pause(true);else runtime.audio.unpause();runtime.lastPaused=state.paused;}}catch(error){runtime.status='error';runtime.detail=error.message;this.store?.diagnostic?.('error','discord',`${runtime.name||'Discord'}: Audioausgabe fehlgeschlagen: ${error.message}`).catch?.(()=>{});}}}
  status(){return [...this.runtimes.entries()].map(([id,r])=>({id,type:r.type,status:r.status||'offline',detail:r.detail||''}));}
  async connect(connection){await this.disconnect(connection.id,true);let runtime;if(connection.type==='discord')runtime=await this.connectDiscord(connection);else if(connection.type==='ts3')runtime=await this.connectTs3(connection);else throw new Error('Unbekannter Verbindungstyp');this.syncPlayback(this.playerStateFor(connection.id),this.resolvePlayerId(connection.id));return runtime;}
  async connectDiscord(c){const {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,ActivityType}=await import('discord.js');const {joinVoiceChannel,createAudioPlayer,createAudioResource,StreamType}=await import('@discordjs/voice');const {PassThrough}=await import('node:stream');const token=this.secrets.open(c.secret);if(!token)throw new Error('Bot-Token fehlt');const intents=[GatewayIntentBits.Guilds,GatewayIntentBits.GuildVoiceStates];if(c.messageContent)intents.push(GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent);const client=new Client({intents}),audio=createAudioPlayer();const runtime={type:'discord',name:c.name,status:'connecting',manual:false,client,audio,ActivityType,joinVoiceChannel,stream:null,backpressured:false,playbackId:null,lastPaused:null,lastPresence:null,prepare:playbackId=>{audio.stop(true);runtime.stream?.destroy();const stream=new PassThrough({highWaterMark:discordPcmBufferBytes}),resource=createAudioResource(stream,{inputType:StreamType.Raw});resource.encoder?.setBitrate(discordOpusBitrate);stream.on('drain',()=>runtime.backpressured=false);runtime.stream=stream;runtime.backpressured=false;runtime.playbackId=playbackId;audio.play(resource);},reset:()=>{audio.stop(true);runtime.stream?.destroy();runtime.stream=null;runtime.backpressured=false;runtime.playbackId=null;runtime.lastPaused=null;},write:b=>writeDiscordPcm(runtime,b),close:async()=>{runtime.manual=true;runtime.voice?.destroy?.();runtime.reset();client.destroy();}};audio.on('error',error=>{runtime.status='error';runtime.detail=error.message;this.store.diagnostic('error','discord',`${c.name}: Audioausgabe fehlgeschlagen: ${error.message}`);});this.runtimes.set(c.id,runtime);this.syncPlayback(this.playerStateFor(c.id),this.resolvePlayerId(c.id));
    client.on('ready',()=>{(async()=>{runtime.status='online';runtime.detail=client.user.tag;this.syncPlayback(this.playerStateFor(c.id),this.resolvePlayerId(c.id));const guild=client.guilds.cache.get(c.guildId);if(!guild){const visible=client.guilds.cache.map(item=>item.name).slice(0,5),message=visible.length?`Discord verbunden – bitte einen erreichbaren Server auswählen. Gefunden: ${visible.join(', ')}`:'Discord verbunden, aber der Bot wurde noch keinem Server hinzugefügt.';runtime.status='warning';runtime.detail=message;await this.store.diagnostic('warn','discord',`${c.name}: ${message}`);return}if(c.voiceChannelId)await this.joinDiscordVoice(c);else{runtime.status='warning';runtime.detail=`${client.user.tag} · kein Voice-Channel ausgewählt`;}const applicationId=client.application?.id||c.clientId;if(!applicationId)throw new Error('Discord Client-ID fehlt');const commands=commandNames.map(name=>new SlashCommandBuilder().setName(name).setDescription(`MusikBot187: ${name}`));commands[0].addStringOption(o=>o.setName('query').setDescription('Titel, Interpret oder URL').setRequired(true));commands[6].addIntegerOption(o=>o.setName('value').setDescription('0–100').setRequired(true).setMinValue(0).setMaxValue(100));await new REST({version:'10'}).setToken(token).put(Routes.applicationGuildCommands(applicationId,guild.id),{body:commands.map(x=>x.toJSON())});})().catch(async error=>{runtime.status='error';runtime.detail=error.message;await this.store.diagnostic('error','discord',`${c.name}: ${error.message}`);});});
    client.on('interactionCreate',i=>{if(!i.isChatInputCommand())return;if(i.guildId!==c.guildId)return i.reply({content:'Dieser Bot-Befehl ist für diesen Discord-Server nicht freigeschaltet.',ephemeral:true});this.handleCommand(i.commandName,i.options.getString('query'),i.options.getInteger('value'),c.id).then(x=>i.reply(String(x).slice(0,1900))).catch(e=>i.reply({content:e.message,ephemeral:true}));});
    client.on('messageCreate',m=>{if(!c.messageContent||!c.prefix||m.author.bot||m.guildId!==c.guildId||!m.content.startsWith(c.prefix))return;const [name,...rest]=m.content.slice(c.prefix.length).trim().split(/\s+/);if(commandNames.includes(name))this.handleCommand(name,rest.join(' '),Number(rest[0]),c.id).then(x=>m.reply(String(x))).catch(e=>m.reply(e.message));});
    client.on('error',e=>this.store.diagnostic('error','discord',e.message));await client.login(token);return runtime;}
  async handleCommand(name,query,value,playerId=null){const player=this.playerFor(playerId);if(name==='play'){const {youtubeSearch}=await import('./media.js');const [item]=await youtubeSearch(query);if(!item)throw new Error('Kein Treffer');player.add(item);return `Hinzugefügt: ${item.title}`;}if(name==='pause')player.pause();if(name==='resume')player.resume();if(name==='skip')player.skip();if(name==='stop')player.stop();if(name==='clear')player.clear();if(name==='volume')player.setVolume(value);if(name==='queue')return player.queue.map((x,i)=>`${i+1}. ${x.title}`).join('\n')||'Queue ist leer.';if(name==='nowplaying')return player.current?.title||'Nichts läuft.';if(name==='help')return commandNames.map(x=>`/${x}`).join(' · ');return 'OK';}
  async joinDiscordVoice(c){const runtime=this.runtimes.get(c.id),client=runtime?.client;if(runtime?.type!=='discord'||!client?.isReady())throw new Error('Discord-Bot ist nicht verbunden. Bitte zuerst „Speichern / verbinden“ wählen.');if(!c.guildId)throw new Error('Discord-Server fehlt.');if(!c.voiceChannelId)throw new Error('Bitte zuerst einen Voice-Channel auswählen.');const guild=client.guilds.cache.get(c.guildId);if(!guild)throw new Error('Der ausgewählte Discord-Server ist für den Bot nicht erreichbar.');const voice=guild.channels.cache.get(c.voiceChannelId);if(!voice?.isVoiceBased?.())throw new Error('Der ausgewählte Voice-Channel wurde nicht gefunden oder ist kein Sprachkanal.');runtime.voice?.destroy?.();const connection=runtime.joinVoiceChannel({channelId:voice.id,guildId:guild.id,adapterCreator:guild.voiceAdapterCreator,selfDeaf:true});connection.subscribe(runtime.audio);runtime.voice=connection;runtime.status='online';runtime.detail=`${client.user?.tag||c.name} · Voice: ${voice.name}`;return {guildId:guild.id,channelId:voice.id,channelName:voice.name};}
  discordOptions(id){const runtime=this.runtimes.get(id),client=runtime?.client;if(!client?.isReady())return {status:runtime?.status||'offline',detail:runtime?.detail||'Discord-Bot ist nicht verbunden.',guilds:[],voiceChannels:[]};const visibleGuilds=[...client.guilds.cache.values()],guilds=visibleGuilds.map(guild=>({id:guild.id,name:guild.name})),voiceChannels=visibleGuilds.flatMap(guild=>[...guild.channels.cache.values()].filter(channel=>channel.isVoiceBased?.()).map(channel=>({id:channel.id,name:channel.name,guildId:guild.id,guildName:guild.name})));return {status:runtime.status||'online',detail:runtime.detail||'',guilds,voiceChannels};}
  async connectTs3(c){const {TeamSpeak}=await import('ts3-nodejs-library');const password=this.secrets.open(c.secret);const client=await TeamSpeak.connect({host:c.host,queryport:Number(c.port||10011),serverport:Number(c.serverPort||9987),username:c.username||'serveradmin',password,nickname:c.nickname||'MusikBot187'});const runtime={type:'ts3',name:c.name,status:'warning',detail:'ServerQuery verbunden · Audio-Transport benötigt einen echten TS3-Client',write:()=>{},close:()=>client.quit()};client.on('error',e=>this.store.diagnostic('error','ts3',e.message));this.runtimes.set(c.id,runtime);return runtime;}
  async disconnect(id,remove=false){const r=this.runtimes.get(id);if(r)await r.close?.();this.runtimes.delete(id);if(remove)this.emit('status',this.status());}
  async close(){for(const id of [...this.runtimes.keys()])await this.disconnect(id);}
}
