import fs from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {assertSafeExternalUrl,safeMusicPath} from './security.js';
export {assertSafeExternalUrl};
export const audioExtensions=new Set(['.mp3','.wav','.flac','.ogg','.opus','.m4a','.aac','.webm']);
export const youtubeRuntimeArgs=['--js-runtimes','node','--remote-components','ejs:github'];
export const searchResultLimit=50;
const headers=[Buffer.from('ID3'),Buffer.from('RIFF'),Buffer.from('fLaC'),Buffer.from('OggS'),Buffer.from([0xff,0xfb]),Buffer.from([0xff,0xf3]),Buffer.from([0xff,0xf2]),Buffer.from([0x1a,0x45,0xdf,0xa3])];
export async function validateAudioFile(file){const h=Buffer.alloc(16);const fd=await fs.open(file,'r');try{await fd.read(h,0,h.length,0);}finally{await fd.close();}if(!headers.some(x=>h.subarray(0,x.length).equals(x))&&!h.subarray(4,8).equals(Buffer.from('ftyp')))throw new Error('Dateiheader ist kein unterstütztes Audioformat');}
export async function listMusic(root){await fs.mkdir(root,{recursive:true});const entries=await fs.readdir(root,{withFileTypes:true});const out=[];for(const e of entries){if(!e.isFile())continue;const p=safeMusicPath(root,e.name);const s=await fs.stat(p);out.push({id:`local:${e.name}`,title:e.name,source:'local',path:e.name,size:s.size});}return out;}
export async function musicBytes(root){return (await listMusic(root)).reduce((n,x)=>n+x.size,0);}
function run(command,args,{timeout=20000,max=1024*1024}={}){return new Promise((resolve,reject)=>{const child=spawn(command,args,{windowsHide:true,stdio:['ignore','pipe','pipe']});let out=Buffer.alloc(0),err='';const timer=setTimeout(()=>child.kill('SIGKILL'),timeout);child.stdout.on('data',b=>{out=Buffer.concat([out,b]);if(out.length>max)child.kill('SIGKILL');});child.stderr.on('data',b=>{err=(err+b).slice(-4096);});child.on('error',reject);child.on('close',code=>{clearTimeout(timer);code===0?resolve(out.toString()):reject(new Error(err||`${command} exit ${code}`));});});}
export async function youtubeSearch(query){const raw=await run('yt-dlp',[...youtubeRuntimeArgs,'--dump-single-json','--flat-playlist','--playlist-end',String(searchResultLimit),'--force-ipv4','--extractor-args','youtube:player_client=web_embedded',`ytsearch${searchResultLimit}:${query}`]);const json=JSON.parse(raw);return (json.entries||[]).slice(0,searchResultLimit).map(x=>({id:x.id,title:x.title,url:x.url?.startsWith('http')?x.url:`https://www.youtube.com/watch?v=${x.id}`,source:'youtube',duration:x.duration,thumbnail:x.thumbnail}));}
export async function radioSearch(query){const url=await assertSafeExternalUrl(`https://de1.api.radio-browser.info/json/stations/search?name=${encodeURIComponent(query)}&limit=${searchResultLimit}&hidebroken=true`);const res=await fetch(url,{headers:{'user-agent':'MusikBot187/5.0'}});if(!res.ok)throw new Error('Radio-Browser nicht erreichbar');return (await res.json()).slice(0,searchResultLimit).map(x=>({id:x.stationuuid,title:x.name,url:x.url_resolved||x.url,source:'radio',thumbnail:x.favicon}));}
export async function spotifySearch(query,id,secret){if(!id||!secret)return[];const tokenRes=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{authorization:`Basic ${Buffer.from(`${id}:${secret}`).toString('base64')}`,'content-type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});if(!tokenRes.ok)throw new Error('Spotify-Anmeldung fehlgeschlagen');const {access_token}=await tokenRes.json();const res=await fetch(`https://api.spotify.com/v1/search?type=track&limit=${searchResultLimit}&q=${encodeURIComponent(query)}`,{headers:{authorization:`Bearer ${access_token}`}});if(!res.ok)throw new Error('Spotify-Suche fehlgeschlagen');return (await res.json()).tracks.items.map(x=>({id:x.id,title:`${x.artists.map(a=>a.name).join(', ')} – ${x.name}`,source:'spotify',url:x.external_urls.spotify,duration:Math.round(x.duration_ms/1000),thumbnail:x.album.images.at(-1)?.url}));}
export function normalizeRadioUrl(raw){return String(raw).replace(/^https?:\/\/streams?\.bigfm\.de\/bigfm-rlp-128-aac\/?(?:[?#].*)?$/i,'https://stream.bigfm.de/rlp/aac-128/stream.bigfm.de/');}
export async function resolveInput(item,musicDir){if(item.source==='local')return safeMusicPath(musicDir,item.path);if(item.source==='youtube'||item.source==='spotify'){const q=item.source==='spotify'?`ytsearch1:${item.title}`:item.url;const out=await run('yt-dlp',[...youtubeRuntimeArgs,'--get-url','-f','bestaudio/best','--force-ipv4','--extractor-args','youtube:player_client=web_embedded',q]);const url=out.trim().split(/\r?\n/)[0];await assertSafeExternalUrl(url);return url;}const url=normalizeRadioUrl(item.url);await assertSafeExternalUrl(url);return url;}
