import fs from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {assertSafeExternalUrl,safeMusicPath} from './security.js';
export {assertSafeExternalUrl};
export const audioExtensions=new Set(['.mp3','.wav','.flac','.ogg','.opus','.m4a','.aac','.webm']);
export const youtubeRuntimeArgs=['--js-runtimes','node','--remote-components','ejs:github'];
export const youtubeClientStrategies=[[],['--extractor-args','youtube:player_client=default'],['--extractor-args','youtube:player_client=web_embedded']];
export const searchResultLimit=50;
export const bestAudioFormat='bestaudio/best';
const headers=[Buffer.from('ID3'),Buffer.from('RIFF'),Buffer.from('fLaC'),Buffer.from('OggS'),Buffer.from([0xff,0xfb]),Buffer.from([0xff,0xf3]),Buffer.from([0xff,0xf2]),Buffer.from([0x1a,0x45,0xdf,0xa3])];
export async function validateAudioFile(file){const h=Buffer.alloc(16);const fd=await fs.open(file,'r');try{await fd.read(h,0,h.length,0);}finally{await fd.close();}if(!headers.some(x=>h.subarray(0,x.length).equals(x))&&!h.subarray(4,8).equals(Buffer.from('ftyp')))throw new Error('Dateiheader ist kein unterstütztes Audioformat');}
export async function listMusic(root){await fs.mkdir(root,{recursive:true});const entries=await fs.readdir(root,{withFileTypes:true});const out=[];for(const e of entries){if(!e.isFile())continue;const p=safeMusicPath(root,e.name);const s=await fs.stat(p);out.push({id:`local:${e.name}`,title:e.name,source:'local',path:e.name,size:s.size});}return out;}
export async function musicBytes(root){return (await listMusic(root)).reduce((n,x)=>n+x.size,0);}
function run(command,args,{timeout=20000,max=1024*1024,signal}={}){return new Promise((resolve,reject)=>{const child=spawn(command,args,{windowsHide:true,stdio:['ignore','pipe','pipe']});let out=Buffer.alloc(0),err='',settled=false,timedOut=false;const finish=(callback,value)=>{if(settled)return;settled=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);callback(value);};const abort=()=>{child.kill('SIGKILL');const error=new Error('Medienauflösung abgebrochen');error.name='AbortError';finish(reject,error);};const timer=setTimeout(()=>{timedOut=true;child.kill('SIGKILL');},timeout);if(signal?.aborted)return abort();signal?.addEventListener('abort',abort,{once:true});child.stdout.on('data',b=>{out=Buffer.concat([out,b]);if(out.length>max){err='Antwort der Medienauflösung ist zu groß';child.kill('SIGKILL');}});child.stderr.on('data',b=>{err=(err+b).slice(-4096);});child.on('error',error=>finish(reject,error));child.on('close',code=>{if(code===0)return finish(resolve,out.toString());finish(reject,new Error(err||(timedOut?`${command} Zeitüberschreitung`:`${command} exit ${code}`)));});});}
export async function youtubeSearch(query){const raw=await run('yt-dlp',[...youtubeRuntimeArgs,'--dump-single-json','--flat-playlist','--playlist-end',String(searchResultLimit),'--force-ipv4',`ytsearch${searchResultLimit}:${query}`]);const json=JSON.parse(raw);return (json.entries||[]).slice(0,searchResultLimit).map(x=>({id:x.id,title:x.title,url:x.url?.startsWith('http')?x.url:`https://www.youtube.com/watch?v=${x.id}`,source:'youtube',duration:x.duration,thumbnail:x.thumbnail,quality:'Beste verfügbare Audioqualität'}));}
export function selectHighestQualityStations(stations,limit=searchResultLimit){const seen=new Set(),selected=[];for(const station of [...stations].sort((a,b)=>Number(b.bitrate||0)-Number(a.bitrate||0))){const identity=[station.name,station.countrycode,station.state].map(value=>String(value||'').trim().toLocaleLowerCase('de-DE')).join('|'),key=identity==='||'?String(station.stationuuid||station.url_resolved||station.url):identity;if(seen.has(key))continue;seen.add(key);selected.push(station);if(selected.length>=limit)break}return selected;}
export async function radioSearch(query){const candidateLimit=searchResultLimit*4,url=await assertSafeExternalUrl(`https://de1.api.radio-browser.info/json/stations/search?name=${encodeURIComponent(query)}&order=bitrate&reverse=true&limit=${candidateLimit}&hidebroken=true`);const res=await fetch(url,{headers:{'user-agent':'MusikBot187/5.0'}});if(!res.ok)throw new Error('Radio-Browser nicht erreichbar');return selectHighestQualityStations(await res.json()).map(x=>({id:x.stationuuid,title:x.name,url:x.url_resolved||x.url,source:'radio',thumbnail:x.favicon,bitrate:Number(x.bitrate||0),codec:String(x.codec||''),quality:[x.codec,Number(x.bitrate)>0?`${Number(x.bitrate)} kbit/s`:null].filter(Boolean).join(' · ')||'Beste verfügbare Streamvariante'}));}
async function spotifyToken(id,secret,fetcher=fetch){if(!id||!secret)throw new Error('Spotify Client-ID und Client-Secret fehlen. Bitte zuerst unter Einstellungen speichern.');const tokenRes=await fetcher('https://accounts.spotify.com/api/token',{method:'POST',headers:{authorization:`Basic ${Buffer.from(`${id}:${secret}`).toString('base64')}`,'content-type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});if(!tokenRes.ok)throw new Error('Spotify-Anmeldung fehlgeschlagen. Bitte Client-ID und Client-Secret prüfen.');return (await tokenRes.json()).access_token;}
async function spotifyJson(url,token,fetcher=fetch){const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.hostname!=='api.spotify.com')throw new Error('Ungültiges Spotify-API-Ziel.');const res=await fetcher(parsed,{headers:{authorization:`Bearer ${token}`}});if(!res.ok){let detail='';try{const body=await res.json();detail=body?.error?.message||body?.error_description||body?.error?.reason||'';}catch{}if(res.status===403)throw new Error('Spotify erlaubt für diese App keinen Zugriff auf die Playlist-Titel. Bei aktuellen Development-Mode-Apps sind nur eigene oder gemeinsam bearbeitete Playlists verfügbar.');if(res.status===429)throw new Error(`Spotify-Limit erreicht${detail?`: ${detail}`:'. Bitte später erneut versuchen.'}`);throw new Error(detail||`Spotify-Anfrage fehlgeschlagen (HTTP ${res.status}).`);}return res.json();}
function spotifyTrack(track){if(!track||track.type&&track.type!=='track')return null;return {id:track.id,title:`${(track.artists||[]).map(artist=>artist.name).filter(Boolean).join(', ')} – ${track.name}`.replace(/^ – /,''),source:'spotify',url:track.external_urls?.spotify||'',duration:Math.round(Number(track.duration_ms||0)/1000),thumbnail:track.album?.images?.at(-1)?.url||'',quality:'Beste verfügbare Audioqualität'};}
export async function spotifySearch(query,id,secret,{fetcher=fetch}={}){if(!id||!secret)return[];const token=await spotifyToken(id,secret,fetcher),items=[];for(let offset=0;offset<searchResultLimit;offset+=10){const page=await spotifyJson(`https://api.spotify.com/v1/search?type=track&limit=10&market=DE&offset=${offset}&q=${encodeURIComponent(query)}`,token,fetcher),tracks=page.tracks?.items||[];items.push(...tracks.map(spotifyTrack).filter(Boolean));if(tracks.length<10)break;}return items.slice(0,searchResultLimit);}
export function parseSpotifyPlaylistId(raw){const value=String(raw||'').trim();const uri=value.match(/^spotify:playlist:([A-Za-z0-9]{10,40})$/i);if(uri)return uri[1];try{const url=new URL(value);if(url.protocol==='https:'&&['open.spotify.com','play.spotify.com'].includes(url.hostname)){const match=url.pathname.match(/^\/playlist\/([A-Za-z0-9]{10,40})(?:\/|$)/);if(match)return match[1];}}catch{}throw new Error('Bitte einen gültigen Spotify-Playlist-Link einfügen.');}
export async function importSpotifyPlaylist(raw,id,secret,{fetcher=fetch,maxItems=500}={}){const playlistId=parseSpotifyPlaylistId(raw),token=await spotifyToken(id,secret,fetcher),data=await spotifyJson(`https://api.spotify.com/v1/playlists/${playlistId}?market=DE`,token,fetcher),items=[];let page=data.items||data.tracks||await spotifyJson(`https://api.spotify.com/v1/playlists/${playlistId}/items?market=DE&limit=50`,token,fetcher);while(page&&items.length<maxItems){for(const entry of page.items||[]){const track=spotifyTrack(entry.item||entry.track);if(track)items.push(track);if(items.length>=maxItems)break;}page=page.next?await spotifyJson(page.next,token,fetcher):null;}return {name:String(data.name||'Spotify-Playlist').slice(0,80),items,source:'spotify',sourceUrl:data.external_urls?.spotify||`https://open.spotify.com/playlist/${playlistId}`,thumbnail:data.images?.at(-1)?.url||'',spotifyId:playlistId};}
export function normalizeRadioUrl(raw){return String(raw).replace(/^https?:\/\/streams?\.bigfm\.de\/bigfm-rlp-128-aac\/?(?:[?#].*)?$/i,'https://stream.bigfm.de/rlp/aac-128/stream.bigfm.de/');}
async function resolveYoutube(q,signal){const failures=[];for(const strategy of youtubeClientStrategies){try{const out=await run('yt-dlp',[...youtubeRuntimeArgs,'--no-playlist','--get-url','-f',bestAudioFormat,'--force-ipv4',...strategy,q],{signal}),url=out.trim().split(/\r?\n/)[0];if(!url)throw new Error('yt-dlp hat keine Audioadresse geliefert.');await assertSafeExternalUrl(url);return url;}catch(error){if(error.name==='AbortError')throw error;failures.push(error.message);}}throw new Error(`YouTube-Audio konnte mit keiner Clientvariante aufgelöst werden. ${failures.at(-1)||''}`.trim());}
export async function resolveInput(item,musicDir,{signal}={}){if(signal?.aborted){const error=new Error('Medienauflösung abgebrochen');error.name='AbortError';throw error;}if(item.source==='local')return safeMusicPath(musicDir,item.path);if(item.source==='youtube'||item.source==='spotify')return resolveYoutube(item.source==='spotify'?`ytsearch1:${item.title}`:item.url,signal);const url=normalizeRadioUrl(item.url);await assertSafeExternalUrl(url);return url;}
