import { EventEmitter } from "node:events";
import { spawn } from "node:child_process";
import { validatePlaybackItem, revalidatePlaybackTarget, validateResolvedMediaUrl } from "./source-policy.js";
import { EgressProxy } from "./egress-proxy.js";

const YTDLP = process.env.MUSIKBOT187_YTDLP || "yt-dlp";
const FFMPEG = process.env.MUSIKBOT187_FFMPEG || "ffmpeg";
const RECOVERY_DELAYS = [2000, 5000, 10000, 20000];
const MAX_QUEUE_ITEMS = 100;
const MAX_YTDLP_STDERR = 256 * 1024;
const USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/151.0 Safari/537.36";
const YOUTUBE_EXTRACTOR_ARGS = "youtube:player_client=web_embedded";

function clampVolume(value) { const n = Number(value); return Number.isFinite(n) ? Math.max(0, Math.min(100, n)) : 0; }
function wait(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }
function rawAudio(buffer, volume) { Object.defineProperty(buffer, "__musikbotVolume", { value: clampVolume(volume), enumerable: false }); return buffer; }
function normalizeItem(item) { if (!item || typeof item !== "object") return item; const value = String(item.url || ""); if (item.source === "radio" && /^https?:\/\/streams\.bigfm\.de\/bigfm-rlp-128-aac\/?$/i.test(value)) return { ...item, url: "https://stream.bigfm.de/rlp/aac-128/stream.bigfm.de/" }; return item; }
function ytdlpArgs(input, output = null) { const args = ["--no-playlist", "--no-warnings", "--js-runtimes", "node", "--force-ipv4", "--add-header", `User-Agent: ${USER_AGENT}`]; const isYoutube = String(input).startsWith("ytsearch") || /(?:youtube\.com|youtu\.be)\//i.test(String(input)); if (String(input).startsWith("ytsearch")) args.push("--default-search", "ytsearch1"); if (isYoutube) args.push("--extractor-args", YOUTUBE_EXTRACTOR_ARGS); args.push("-f", "bestaudio/best"); if (output) args.push("-o", output); args.push(input); return args; }

export class Player extends EventEmitter {
  queue = []; current = null; paused = false; volume; mode; ff = null; resolver = null; generation = 0; spawnFn; settings; egressProxy = ""; proxyServer = null;
  constructor(settings, { spawnFn = spawn } = {}) { super(); this.settings = settings; this.volume = clampVolume(settings.volume ?? 80); this.mode = ["queue", "repeat", "shuffle"].includes(settings.mode) ? settings.mode : "queue"; this.spawnFn = spawnFn; }
  async ensureEgressProxy() { if (this.proxyServer) return this.egressProxy; this.proxyServer = await new EgressProxy().start(); this.egressProxy = this.proxyServer.url; return this.egressProxy; }
  get dataDirectory() { return this.settings.filesDirectory; }
  snapshot() { return { queue: this.queue, current: this.current, paused: this.paused, volume: this.volume, mode: this.mode }; }
  setVolume(value) { this.volume = clampVolume(value); this.emit("state"); this.emit("volume", this.volume); }
  setMode(mode) { if (["queue", "repeat", "shuffle"].includes(mode)) this.mode = mode; }
  pause() { this.paused = true; for (const child of [this.resolver, this.ff]) if (child) try { child.kill("SIGSTOP"); } catch {} }
  resume() { this.paused = false; for (const child of [this.resolver, this.ff]) if (child) try { child.kill("SIGCONT"); } catch {} }
  stop() { this.generation++; this.emit("audio-reset"); for (const child of [this.resolver, this.ff]) if (child) try { child.kill("SIGTERM"); } catch {}; this.resolver = null; this.ff = null; this.queue = []; this.current = null; this.paused = false; this.emit("state"); }
  async shutdown() { this.stop(); if (this.proxyServer) { await this.proxyServer.stop().catch(() => {}); this.proxyServer = null; this.egressProxy = ""; } await new Promise(resolve => setImmediate(resolve)); }
  skip() { this.generation++; this.emit("audio-reset"); for (const child of [this.resolver, this.ff]) if (child) try { child.kill("SIGTERM"); } catch {}; this.resolver = null; this.ff = null; if (this.current || this.queue.length) void this.next(); }
  clear() { this.queue = []; this.emit("state"); }
  async remove(index) { if (Number.isInteger(index) && index >= 0 && index < this.queue.length) this.queue.splice(index, 1); this.emit("state"); }
  async enqueue(items, { playNow = false } = {}) { const clean = Array.isArray(items) ? items.filter(x => x && typeof x.url === "string" && x.url.trim()).slice(0, MAX_QUEUE_ITEMS) : []; const validated = []; for (const raw of clean) validated.push(await validatePlaybackItem(normalizeItem(raw), this.dataDirectory)); if (playNow) { this.generation++; this.emit("audio-reset"); for (const child of [this.resolver, this.ff]) if (child) try { child.kill("SIGTERM"); } catch {}; this.resolver = null; this.ff = null; this.queue = validated.slice(0, MAX_QUEUE_ITEMS); this.current = null; this.paused = false; void this.next(); return; } const room = Math.max(0, MAX_QUEUE_ITEMS - this.queue.length); this.queue.push(...validated.slice(0, room)); if (!this.current) void this.next(); else this.emit("state"); }
  async resolve(item) { const input = String(item.url); const args = ytdlpArgs(input); args.splice(args.indexOf("-f"), 2, "-f", "bestaudio/best", "-g"); const p = this.spawnFn(YTDLP, args, { stdio: ["ignore", "pipe", "pipe"] }); this.resolver = p; let out = "", err = "", settled = false; await new Promise((resolve, reject) => { const finish = (fn, value) => { if (settled) return; settled = true; clearTimeout(timer); fn(value); }; const timer = setTimeout(() => { try { p.kill("SIGTERM"); } catch {}; finish(reject, new Error("Zeitüberschreitung beim Auflösen der Audioquelle")); }, 20000); p.stdout.on("data", d => { out += String(d); if (out.length > 1024 * 1024) { try { p.kill("SIGTERM"); } catch {}; finish(reject, new Error("Aufgelöste Medienquelle ist zu groß")); } }); p.stderr.on("data", d => { err += String(d); if (Buffer.byteLength(err, "utf8") > MAX_YTDLP_STDERR) err = err.slice(-MAX_YTDLP_STDERR); }); p.on("error", e => finish(reject, e)); p.on("close", code => code === 0 ? finish(resolve) : finish(reject, new Error(err.trim() || "yt-dlp konnte die Quelle nicht öffnen"))); }); if (this.resolver === p) this.resolver = null; const url = out.trim().split(/\r?\n/)[0]; if (!url) throw new Error("yt-dlp hat keine abspielbare URL geliefert"); await validateResolvedMediaUrl(url); return url; }
  async playYtdlp(item, run) { const input = String(item.url); const args = ytdlpArgs(input, "-"); const yt = this.spawnFn(YTDLP, args, { stdio: ["ignore", "pipe", "pipe"] }); const ffArgs = ["-hide_banner", "-loglevel", "error", "-nostdin", "-re", "-i", "pipe:0", "-vn", "-f", "s16le", "-ar", "48000", "-ac", "2", "pipe:1"]; const ff = this.spawnFn(FFMPEG, ffArgs, { stdio: ["pipe", "pipe", "pipe"] }); this.resolver = yt; this.ff = ff; let ytError = ""; yt.stderr.on("data", d => { ytError += String(d); if (Buffer.byteLength(ytError, "utf8") > MAX_YTDLP_STDERR) ytError = ytError.slice(-MAX_YTDLP_STDERR); }); yt.stdout.pipe(ff.stdin); yt.on("error", () => { try { ff.kill("SIGTERM"); } catch {} }); yt.on("close", code => { if (code !== 0 && run === this.generation) { this.emit("diagnostic", ytError.trim().slice(0, 1000) || "yt-dlp konnte den YouTube-Stream nicht liefern"); try { ff.kill("SIGTERM"); } catch {} } }); if (this.paused) { try { yt.kill("SIGSTOP"); } catch {} try { ff.kill("SIGSTOP"); } catch {} } ff.stdout.on("data", d => { if (run === this.generation && this.ff === ff) this.emit("audio", rawAudio(Buffer.from(d), this.volume)); }); ff.stderr.on("data", d => { if (run === this.generation && this.ff === ff) { const message = String(d).trim(); if (message) this.emit("diagnostic", message.slice(0, 1000)); } }); const code = await new Promise(resolve => { ff.on("error", () => resolve(-1)); ff.on("close", value => resolve(value)); }); if (yt.exitCode === null) { try { yt.kill("SIGTERM"); } catch {} } if (this.ff === ff) this.ff = null; if (this.resolver === yt) this.resolver = null; if (run !== this.generation) return "cancelled"; if (yt.exitCode !== null && yt.exitCode !== 0) return "failed"; return code === 0 ? "ended" : "failed"; }
  async playSource(rawItem, run) { const item = normalizeItem(rawItem); await revalidatePlaybackTarget(item, this.dataDirectory); if (run !== this.generation) return "cancelled"; this.emit("audio-reset"); if (item.source === "youtube" || item.source === "spotify" || String(item.url).startsWith("ytsearch")) return this.playYtdlp(item, run); const source = item.source === "radio" || item.source === "file" || item.source === "direct" ? String(item.url) : await this.resolve(item); const ffArgs = ["-hide_banner", "-loglevel", "error", "-nostdin"]; if (item.source !== "file") ffArgs.push("-reconnect", "1", "-reconnect_streamed", "1", "-reconnect_at_eof", "1", "-reconnect_on_network_error", "1", "-reconnect_on_http_error", "4xx,5xx", "-reconnect_delay_max", "5"); if (item.source === "radio" || item.source === "direct") ffArgs.push("-http_proxy", await this.ensureEgressProxy()); ffArgs.push("-i", source, "-vn", "-f", "s16le", "-ar", "48000", "-ac", "2", "pipe:1"); const ff = this.spawnFn(FFMPEG, ffArgs, { stdio: ["ignore", "pipe", "pipe"] }); this.ff = ff; if (this.paused) try { ff.kill("SIGSTOP"); } catch {} ff.stdout.on("data", d => { if (run === this.generation && this.ff === ff) this.emit("audio", rawAudio(Buffer.from(d), this.volume)); }); ff.stderr.on("data", d => { if (run === this.generation && this.ff === ff) { const message = String(d).trim(); if (message) this.emit("diagnostic", message.slice(0, 1000)); } }); const code = await new Promise(resolve => { ff.on("error", () => resolve(-1)); ff.on("close", value => resolve(value)); }); if (this.ff === ff) this.ff = null; if (run !== this.generation) return "cancelled"; return code === 0 ? "ended" : "failed"; }
  async recover(item, run, reason) { for (let attempt = 0; attempt < RECOVERY_DELAYS.length; attempt++) { if (run !== this.generation) return false; const delay = RECOVERY_DELAYS[attempt]; this.emit("diagnostic", `Audio-Verbindung verloren (${String(reason).slice(0, 300)}). Wiederverbindung in ${Math.round(delay / 1000)}s – Versuch ${attempt + 1}/${RECOVERY_DELAYS.length}.`); await wait(delay); if (run !== this.generation) return false; try { const result = await this.playSource(item, run); if (result === "ended") return true; if (result === "cancelled") return false; this.emit("diagnostic", `Wiederverbindungsversuch ${attempt + 1} fehlgeschlagen.`); } catch (error) { this.emit("diagnostic", `Wiederverbindungsversuch ${attempt + 1} fehlgeschlagen: ${error instanceof Error ? error.message : String(error)}`.slice(0, 1000)); } } return false; }
  async next() { if (!this.queue.length) { this.current = null; this.paused = false; this.emit("state"); return; } let item = this.queue.shift(); if (this.mode === "shuffle" && this.queue.length) { const index = Math.floor(Math.random() * (this.queue.length + 1)); if (index < this.queue.length) { const randomItem = this.queue.splice(index, 1)[0]; this.queue.unshift(item); item = randomItem; } } this.current = item; this.emit("state"); const run = ++this.generation; try { let result; try { result = await this.playSource(item, run); } catch (error) { if (run !== this.generation) return; const recovered = await this.recover(item, run, error instanceof Error ? error.message : String(error)); if (!recovered) throw error; result = "ended"; } if (run !== this.generation) return; if (result === "failed") { const recovered = await this.recover(item, run, "FFmpeg/yt-dlp wurde unerwartet beendet"); if (!recovered) this.emit("diagnostic", "Audio konnte nach mehreren Wiederverbindungsversuchen nicht wiederhergestellt werden."); } if (run !== this.generation) return; if (this.mode === "repeat" && this.queue.length < MAX_QUEUE_ITEMS) this.queue.unshift(item); await this.next(); } catch (error) { if (this.resolver) this.resolver = null; if (run === this.generation) { this.emit("diagnostic", error instanceof Error ? error.message : String(error)); await this.next(); } } }
}
