import {EventEmitter} from 'node:events';
import {spawn} from 'node:child_process';
import {resolveInput} from './media.js';
export const queueLimit=500;
export function scalePcm16le(buffer,volume){const level=Math.max(0,Math.min(100,Number(volume)))/100;if(level===1)return buffer;const output=Buffer.allocUnsafe(buffer.length);let i=0;for(;i+1<buffer.length;i+=2){const sample=Math.round(buffer.readInt16LE(i)*level);output.writeInt16LE(Math.max(-32768,Math.min(32767,sample)),i);}if(i<buffer.length)output[i]=buffer[i];return output;}
export class PcmVolumeScaler{
  constructor(volume=100,{rampMs=60,sampleRate=48000,channels=2}={}){this.rampSamples=Math.max(1,Math.round(sampleRate*channels*rampMs/1000));this.current=this.target=Math.max(0,Math.min(100,Number(volume)))/100;this.remaining=0;}
  setVolume(volume){this.target=Math.max(0,Math.min(100,Number(volume)))/100;this.remaining=this.rampSamples;}
  process(buffer){if(this.remaining===0&&this.current===1)return buffer;const output=Buffer.allocUnsafe(buffer.length);let i=0;for(;i+1<buffer.length;i+=2){if(this.remaining>0){this.current+=(this.target-this.current)/this.remaining;this.remaining--;if(this.remaining===0)this.current=this.target;}const sample=Math.round(buffer.readInt16LE(i)*this.current);output.writeInt16LE(Math.max(-32768,Math.min(32767,sample)),i);}if(i<buffer.length)output[i]=buffer[i];return output;}
}
export function isTransientPlaybackError(error){return /(?:network|timed?\s*out|timeout|connection|connect|econn|enotfound|eai_again|temporary|temporarily|name resolution|remote end closed|end of file|input\/output error|http error (?:403|408|425|429|5\d\d)|server returned (?:403|408|425|429|5\d\d))/i.test(String(error||''));}
export function ffmpegArgs(input,resumeSeconds=0,live=false){const args=['-nostdin','-hide_banner','-loglevel','warning'];if(/^https?:/.test(input)){args.push('-reconnect','1','-reconnect_streamed','1','-reconnect_on_network_error','1','-reconnect_on_http_error','4xx,5xx','-reconnect_delay_max','30');if(live)args.push('-reconnect_at_eof','1','-thread_queue_size','4096','-fflags','+genpts+discardcorrupt');}if(!live)args.push('-re');if(resumeSeconds>=1)args.push('-ss',String(Math.floor(resumeSeconds)));args.push('-i',input,'-vn','-af','aresample=async=1000:min_hard_comp=0.100:first_pts=0','-ar','48000','-ac','2','-f','s16le','pipe:1');return args;}
export class Player extends EventEmitter{
  constructor({musicDir,diagnostic}){super();this.musicDir=musicDir;this.diagnostic=diagnostic;this.queue=[];this.current=null;this.volume=75;this.volumeScaler=new PcmVolumeScaler(this.volume);this.mode='queue';this.paused=false;this.generation=0;this.process=null;this.resolver=null;this.retries=[2000,5000,10000,20000,30000,60000];this.retryTimer=null;this.reconnecting=false;this.retryAt=null;this.startedAt=null;this.elapsedSeconds=0;}
  position(){return this.elapsedSeconds+(this.startedAt&&!this.paused?(Date.now()-this.startedAt)/1000:0);}
  state(){return {current:this.current,queue:this.queue,volume:this.volume,mode:this.mode,paused:this.paused,playing:Boolean(this.process),resolving:Boolean(this.resolver),reconnecting:this.reconnecting,retryAt:this.retryAt,positionSeconds:Math.floor(this.position()),playbackId:this.current?this.generation:null};}
  snapshot(){return {version:1,current:this.current,queue:this.queue,volume:this.volume,mode:this.mode,positionSeconds:Math.floor(this.position()),savedAt:new Date().toISOString()};}
  restore(snapshot){if(!snapshot||snapshot.version!==1)return false;const current=snapshot.current&&typeof snapshot.current==='object'?snapshot.current:null,queue=Array.isArray(snapshot.queue)?snapshot.queue.filter(Boolean).slice(0,queueLimit):[];this.volume=Number.isFinite(Number(snapshot.volume))?Math.max(0,Math.min(100,Number(snapshot.volume))):this.volume;this.volumeScaler=new PcmVolumeScaler(this.volume);this.mode=['queue','repeat','shuffle'].includes(snapshot.mode)?snapshot.mode:'queue';this.queue=queue;if(!current){this.emit('state',this.state());return false;}const selectedMode=this.mode;this.mode='queue';this.queue.unshift(current);this.next(0,Math.max(0,Number(snapshot.positionSeconds)||0));this.mode=selectedMode;return true;}
  add(items,{now=false}={}){const list=(Array.isArray(items)?items:[items]).filter(Boolean);if(this.queue.length+list.length>queueLimit)throw new Error(`Warteschlangen-Limit von ${queueLimit} Titeln überschritten`);if(now){this.queue.unshift(...list);this.skip();}else{this.queue.push(...list);if(!this.current)this.next();}this.emit('state',this.state());}
  remove(index){if(!Number.isInteger(index)||index<0||index>=this.queue.length)throw new Error('Ungültiger Queue-Index');this.queue.splice(index,1);this.emit('state',this.state());}
  clear(){this.queue=[];this.emit('state',this.state());}
  setVolume(v){v=Number(v);if(!Number.isFinite(v)||v<0||v>100)throw new Error('Lautstärke 0–100');this.volume=v;this.volumeScaler.setVolume(v);this.emit('state',this.state());}
  setMode(v){if(!['queue','repeat','shuffle'].includes(v))throw new Error('Ungültiger Modus');this.mode=v;this.emit('state',this.state());}
  pause(){if(this.current&&!this.paused){if(this.startedAt)this.elapsedSeconds+=(Date.now()-this.startedAt)/1000;this.startedAt=null;this.process?.kill('SIGSTOP');this.paused=true;this.emit('state',this.state());}}
  resume(){if(this.current&&this.paused){this.process?.kill('SIGCONT');this.paused=false;if(this.process)this.startedAt=Date.now();this.emit('state',this.state());}}
  stop({clear=true}={}){this.generation++;clearTimeout(this.retryTimer);this.retryTimer=null;this.resolver?.abort();this.resolver=null;if(this.process)this.process.kill('SIGKILL');this.process=null;this.current=null;this.paused=false;this.reconnecting=false;this.retryAt=null;this.startedAt=null;this.elapsedSeconds=0;if(clear)this.queue=[];this.emit('state',this.state());}
  skip(){this.stop({clear:false});this.next();}
  async next(attempt=0,resumeSeconds=0){if(this.current||!this.queue.length)return;const item=this.mode==='shuffle'?this.queue.splice(Math.floor(Math.random()*this.queue.length),1)[0]:this.queue.shift();this.current=item;this.paused=false;this.reconnecting=false;this.retryAt=null;this.elapsedSeconds=item.source==='radio'?0:resumeSeconds;this.startedAt=null;const generation=++this.generation,controller=this.resolver=new AbortController();this.emit('state',this.state());try{const input=await resolveInput(item,this.musicDir,{signal:controller.signal});if(generation!==this.generation)return;this.resolver=null;const child=this.process=spawn('ffmpeg',ffmpegArgs(input,item.source==='radio'?0:resumeSeconds,item.source==='radio'),{stdio:['ignore','pipe','pipe']});this.startedAt=this.paused?null:Date.now();child.stdout.on('data',b=>this.emit('pcm',this.volumeScaler.process(b)));let errors='',finished=false;const finishOnce=(code,error)=>{if(finished)return;finished=true;this.finish(generation,code,error,attempt);};child.stderr.on('data',b=>errors=(errors+b).slice(-4000));child.on('error',e=>finishOnce(1,e.message));child.on('close',code=>finishOnce(code,errors));if(this.paused)child.kill('SIGSTOP');if(attempt>0)this.diagnostic('info','player',`${item.title||'Titel'}: Verbindung wiederhergestellt, Wiedergabe fortgesetzt.`);this.emit('state',this.state());}catch(e){if(e.name!=='AbortError')this.finish(generation,1,e.message,attempt);}}
  finish(generation,code,error,attempt){if(generation!==this.generation)return;const resumeSeconds=this.position(),prior=this.current,errorText=String(error||`FFmpeg exit ${code}`);this.process=null;this.resolver=null;this.startedAt=null;this.paused=false;if(code&&(attempt<this.retries.length||isTransientPlaybackError(errorText))){const delay=this.retries[Math.min(attempt,this.retries.length-1)];this.reconnecting=true;this.retryAt=Date.now()+delay;this.elapsedSeconds=prior?.source==='radio'?0:resumeSeconds;this.current=prior;this.diagnostic('warn','player',`${prior?.title||'Wiedergabe'}: Verbindung unterbrochen. Neuer Versuch in ${Math.ceil(delay/1000)} Sekunden. ${errorText}`);this.retryTimer=setTimeout(()=>{if(generation!==this.generation)return;this.retryTimer=null;this.current=null;this.reconnecting=false;this.retryAt=null;this.queue.unshift(prior);this.next(attempt+1,this.elapsedSeconds);},delay);}else{this.current=null;this.reconnecting=false;this.retryAt=null;this.elapsedSeconds=0;if(code)this.diagnostic('error','player',errorText);if(this.mode==='repeat'&&prior)this.queue.unshift(prior);this.next();}this.emit('state',this.state());}
}
