export const resourceLearningMs=24*60*60_000;
export const resourceHistoryMs=7*24*60*60_000;
export const resourceHistoryLimit=2016;
const mib=1024*1024;
const finite=value=>Number.isFinite(Number(value));
const average=values=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;
const percentile=(values,fraction)=>{const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.max(0,Math.ceil(sorted.length*fraction)-1)]||0};
const rounded=(value,digits=1)=>Math.round(value*10**digits)/10**digits;
const roundMemory=value=>Math.ceil(value/(256*mib))*256*mib;
const roundBandwidth=value=>Math.ceil(Math.max(0,value)*10)/10;

export function recordResourceSample(data,system,now=new Date()){
  const cpuPercent=Number(system?.cpu?.busyPercent),cores=Number(system?.cpu?.cores),memoryUsed=Number(system?.memory?.used),memoryTotal=Number(system?.memory?.total),rxBytesPerSecond=Number(system?.network?.rxPerSecond),txBytesPerSecond=Number(system?.network?.txPerSecond),time=now.getTime();
  if(!data||!finite(cpuPercent)||!finite(cores)||cores<1||!finite(memoryUsed)||!finite(memoryTotal)||memoryTotal<=0||!Number.isFinite(time))return false;
  if(!Array.isArray(data.resourceHistory))data.resourceHistory=[];
  data.resourceHistory.push({time:new Date(time).toISOString(),cpuPercent:Math.max(0,Math.min(100,cpuPercent)),cores:Math.max(1,Math.round(cores)),memoryUsed:Math.max(0,memoryUsed),memoryTotal:Math.max(1,memoryTotal),...(finite(rxBytesPerSecond)&&finite(txBytesPerSecond)?{rxBytesPerSecond:Math.max(0,rxBytesPerSecond),txBytesPerSecond:Math.max(0,txBytesPerSecond)}:{})});
  const cutoff=time-resourceHistoryMs;data.resourceHistory=data.resourceHistory.filter(sample=>Date.parse(sample.time)>=cutoff).slice(-resourceHistoryLimit);return true;
}

export function resourceAdvisor(data,now=new Date()){
  const cutoff=now.getTime()-resourceHistoryMs,samples=(Array.isArray(data?.resourceHistory)?data.resourceHistory:[]).filter(sample=>Date.parse(sample.time)>=cutoff&&finite(sample.cpuPercent)&&finite(sample.cores)&&finite(sample.memoryUsed)&&finite(sample.memoryTotal)&&Number(sample.memoryTotal)>0).sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));
  if(!samples.length)return {samples:0,collectedHours:0,learningHours:24,progressPercent:0,ready:false,cpu:null,memory:null,network:null,recommendation:null};
  const cpuPercent=samples.map(sample=>Math.max(0,Math.min(100,Number(sample.cpuPercent)))),coreUse=samples.map((sample,index)=>cpuPercent[index]/100*Math.max(1,Number(sample.cores))),memoryUsed=samples.map(sample=>Math.max(0,Number(sample.memoryUsed))),memoryPercent=samples.map(sample=>Math.max(0,Math.min(100,Number(sample.memoryUsed)/Number(sample.memoryTotal)*100))),networkSamples=samples.filter(sample=>finite(sample.rxBytesPerSecond)&&finite(sample.txBytesPerSecond)),rxRates=networkSamples.map(sample=>Math.max(0,Number(sample.rxBytesPerSecond))),txRates=networkSamples.map(sample=>Math.max(0,Number(sample.txBytesPerSecond))),first=Date.parse(samples[0].time),last=Date.parse(samples.at(-1).time),span=Math.max(0,last-first),ready=span>=resourceLearningMs-30*60_000&&samples.length>=144,p95Cores=percentile(coreUse,.95),p95Memory=percentile(memoryUsed,.95),p95Rx=percentile(rxRates,.95),p95Tx=percentile(txRates,.95),minimumCores=Math.max(1,Math.ceil(p95Cores/.85)),optimalCores=Math.max(minimumCores,Math.ceil(p95Cores/.6)),minimumMemory=roundMemory(Math.max(1024*mib,p95Memory*1.2)),optimalMemory=roundMemory(Math.max(minimumMemory,p95Memory*1.5)),minimumDownload=roundBandwidth(Math.max(1,p95Rx*8/1_000_000*1.5)),minimumUpload=roundBandwidth(Math.max(.5,p95Tx*8/1_000_000*1.5)),optimalDownload=roundBandwidth(Math.max(5,p95Rx*8/1_000_000*2.5)),optimalUpload=roundBandwidth(Math.max(2,p95Tx*8/1_000_000*2.5)),network=networkSamples.length?{samples:networkSamples.length,averageRxBytesPerSecond:Math.round(average(rxRates)),minimumRxBytesPerSecond:Math.round(Math.min(...rxRates)),maximumRxBytesPerSecond:Math.round(Math.max(...rxRates)),p95RxBytesPerSecond:Math.round(p95Rx),averageTxBytesPerSecond:Math.round(average(txRates)),minimumTxBytesPerSecond:Math.round(Math.min(...txRates)),maximumTxBytesPerSecond:Math.round(Math.max(...txRates)),p95TxBytesPerSecond:Math.round(p95Tx)}:null;
  return {samples:samples.length,collectedHours:rounded(span/3_600_000,1),learningHours:24,progressPercent:Math.min(100,Math.round(span/resourceLearningMs*100)),ready,cpu:{allocatedCores:Number(samples.at(-1).cores),averagePercent:rounded(average(cpuPercent)),minimumPercent:rounded(Math.min(...cpuPercent)),maximumPercent:rounded(Math.max(...cpuPercent)),p95Percent:rounded(percentile(cpuPercent,.95)),averageCores:rounded(average(coreUse),2),maximumCores:rounded(Math.max(...coreUse),2),p95Cores:rounded(p95Cores,2)},memory:{totalBytes:Number(samples.at(-1).memoryTotal),averageBytes:Math.round(average(memoryUsed)),minimumBytes:Math.round(Math.min(...memoryUsed)),maximumBytes:Math.round(Math.max(...memoryUsed)),p95Bytes:Math.round(p95Memory),averagePercent:rounded(average(memoryPercent)),minimumPercent:rounded(Math.min(...memoryPercent)),maximumPercent:rounded(Math.max(...memoryPercent)),p95Percent:rounded(percentile(memoryPercent,.95))},network,recommendation:ready?{minimum:{cores:minimumCores,memoryBytes:minimumMemory,downloadMbps:minimumDownload,uploadMbps:minimumUpload},optimal:{cores:optimalCores,memoryBytes:optimalMemory,downloadMbps:optimalDownload,uploadMbps:optimalUpload},basis:'95-Prozent-Wert mit Reserve'}:null};
}
