import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import Fastify from 'fastify';
import cors from '@fastify/cors';
import multipart from '@fastify/multipart';
import fastifyStatic from '@fastify/static';
import {config} from './config.js';
import {Store} from './store.js';
import {Player} from './player.js';
import {IntegrationManager} from './integrations.js';
import {SecretBox,RateLimiter,hashPassword,verifyPassword,timingEqual,validUsername,validAccent,permissions,safeMusicPath} from './security.js';
import {youtubeSearch,radioSearch,spotifySearch,listMusic,musicBytes,validateAudioFile,audioExtensions} from './media.js';
import {metrics} from './monitoring.js';
import {control} from './control-client.js';

export async function buildServer(options={}){
  const cfg={...config,...options};await fs.mkdir(cfg.musicDir,{recursive:true});let key;try{key=(await fs.readFile(cfg.secretFile,'utf8')).trim();}catch{key=crypto.randomBytes(32).toString('hex');await fs.writeFile(cfg.secretFile,key,{mode:0o600});}const secrets=SecretBox.fromHex(key);const store=await new Store(cfg.stateFile).load();const player=new Player({musicDir:cfg.musicDir,diagnostic:(...x)=>store.diagnostic(...x)});const integrations=new IntegrationManager({player,store,secrets});
  const app=Fastify({logger:options.logger??true,bodyLimit:1024*1024,trustProxy:false});const loginLimit=new RateLimiter(5,60_000),searchLimit=new RateLimiter(30,60_000),playLimit=new RateLimiter(60,60_000);
  await app.register(cors,{origin:false});await app.register(multipart,{limits:{fileSize:cfg.maxUpload,files:1}});await app.register(fastifyStatic,{root:cfg.frontendDir,wildcard:false});
  app.addHook('onRequest',async(req,reply)=>{reply.headers({'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=()','cache-control':'no-store'});req.user=null;const token=req.headers.authorization?.match(/^Bearer (.+)$/)?.[1];if(token)req.user=store.auth(token);});
  const auth=permission=>async(req,reply)=>{if(!req.user)return reply.code(401).send({error:'Anmeldung erforderlich'});const granted=req.user.role==='admin'?permissions:req.user.permissions||[];if(permission&&!granted.includes(permission))return reply.code(403).send({error:'Berechtigung fehlt'});};
  const tokenOf=req=>req.headers.authorization?.slice(7)||'';const id=()=>crypto.randomUUID();
  app.get('/api/health',async()=>({ok:true,version:'5.0.0',setupRequired:store.data.users.length===0}));
  app.get('/api/setup',async(req,reply)=>({required:store.data.users.length===0,tokenRequired:store.data.users.length===0}));
  app.post('/api/setup',async(req,reply)=>{if(store.data.users.length)return reply.code(409).send({error:'Setup abgeschlossen'});if(!cfg.setupToken||!timingEqual(req.headers['x-musikbot-setup-token'],cfg.setupToken))return reply.code(403).send({error:'Setup-Token ungültig'});const {username,password}=req.body||{};if(!validUsername(username))return reply.code(400).send({error:'Ungültiger Benutzername'});const user={id:id(),username,passwordHash:hashPassword(password),role:'admin',permissions};store.data.users.push(user);const token=store.createSession(user,cfg.sessionTtlMs,cfg.maxSessions);await store.save();return {token,user:store.publicUser(user)};});
  app.post('/api/auth/login',async(req,reply)=>{const key=`${req.ip}:${req.body?.username||''}`;if(!loginLimit.take(key))return reply.code(429).send({error:'Zu viele Loginversuche'});const user=store.data.users.find(u=>u.username===req.body?.username);if(!user||!verifyPassword(req.body?.password,user.passwordHash))return reply.code(401).send({error:'Anmeldedaten falsch'});const token=store.createSession(user,cfg.sessionTtlMs,cfg.maxSessions);await store.save();return {token,user:store.publicUser(user)};});
  app.post('/api/auth/logout',{preHandler:auth()},async req=>{store.revoke(tokenOf(req));await store.save();return {ok:true};});app.get('/api/auth/me',{preHandler:auth()},async req=>({user:store.publicUser(req.user)}));
  app.post('/api/auth/password',{preHandler:auth()},async(req,reply)=>{if(!verifyPassword(req.body?.current,req.user.passwordHash))return reply.code(400).send({error:'Aktuelles Passwort falsch'});req.user.passwordHash=hashPassword(req.body.next);store.data.sessions=store.data.sessions.filter(s=>s.userId!==req.user.id);await store.save();return {ok:true};});
  app.get('/api/state',{preHandler:auth()},async()=>({player:player.state(),settings:store.redact().settings,connections:store.redact().connections,runtimes:integrations.status()}));
  app.get('/api/search',{preHandler:auth()},async(req,reply)=>{const source=req.query.source||'all',q=String(req.query.q||'').trim();if(!q)return[];if(!searchLimit.take(`${req.ip}:${req.user.id}`))return reply.code(429).send({error:'Suchlimit erreicht'});const jobs=[];if(source==='all'||source==='youtube')jobs.push(youtubeSearch(q));if(source==='all'||source==='radio')jobs.push(radioSearch(q));if(source==='all'||source==='spotify')jobs.push(spotifySearch(q,store.data.settings.spotifyClientId,secrets.open(store.data.settings.spotifySecret)));const settled=await Promise.allSettled(jobs);return settled.flatMap(x=>x.status==='fulfilled'?x.value:[]);});
  app.post('/api/player/queue',{preHandler:auth('player.control')},async(req,reply)=>{if(!playLimit.take(`${req.ip}:${req.user.id}`))return reply.code(429).send({error:'Wiedergabelimit erreicht'});player.add(req.body?.items||req.body?.item,{now:Boolean(req.body?.now)});return player.state();});
  app.delete('/api/player/queue/:index',{preHandler:auth('player.control')},async req=>{player.remove(Number(req.params.index));return player.state();});app.delete('/api/player/queue',{preHandler:auth('player.control')},async()=>{player.clear();return player.state();});
  for(const action of ['pause','resume','skip','stop'])app.post(`/api/player/${action}`,{preHandler:auth('player.control')},async()=>{player[action]();return player.state();});
  app.put('/api/player/volume',{preHandler:auth('player.control')},async req=>{player.setVolume(req.body?.value);return player.state();});app.put('/api/player/mode',{preHandler:auth('player.control')},async req=>{player.setMode(req.body?.mode);return player.state();});
  app.get('/api/playlists',{preHandler:auth()},async()=>store.data.playlists);app.post('/api/playlists',{preHandler:auth('playlists.manage')},async req=>{const p={id:id(),name:String(req.body?.name||'Neue Playlist').slice(0,80),items:(req.body?.items||[]).slice(0,cfg.maxPlaylist)};store.data.playlists.push(p);await store.save();return p;});
  app.put('/api/playlists/:id',{preHandler:auth('playlists.manage')},async(req,reply)=>{const p=store.data.playlists.find(x=>x.id===req.params.id);if(!p)return reply.code(404).send({error:'Nicht gefunden'});if(req.body.name)p.name=String(req.body.name).slice(0,80);if(Array.isArray(req.body.items))p.items=req.body.items.slice(0,cfg.maxPlaylist);await store.save();return p;});app.delete('/api/playlists/:id',{preHandler:auth('playlists.manage')},async req=>{store.data.playlists=store.data.playlists.filter(x=>x.id!==req.params.id);await store.save();return {ok:true};});
  app.get('/api/music',{preHandler:auth()},async()=>listMusic(cfg.musicDir));app.post('/api/music/upload',{preHandler:auth('music.manage')},async(req,reply)=>{const part=await req.file();if(!part)return reply.code(400).send({error:'Datei fehlt'});const ext=path.extname(part.filename).toLowerCase();if(!audioExtensions.has(ext))return reply.code(400).send({error:'Audioformat nicht erlaubt'});const target=safeMusicPath(cfg.musicDir,path.basename(part.filename));const before=await musicBytes(cfg.musicDir);let written=0;const handle=await fs.open(`${target}.upload`,'wx',0o600);try{for await(const chunk of part.file){written+=chunk.length;if(before+written>cfg.musicQuota)throw new Error('Musikquote überschritten');await handle.write(chunk);}await handle.close();await validateAudioFile(`${target}.upload`);await fs.rename(`${target}.upload`,target);}catch(e){await handle.close().catch(()=>{});await fs.rm(`${target}.upload`,{force:true});throw e;}return {ok:true,file:path.basename(target)};});app.delete('/api/music/:name',{preHandler:auth('music.manage')},async req=>{await fs.unlink(safeMusicPath(cfg.musicDir,req.params.name));return {ok:true};});
  app.get('/api/connections',{preHandler:auth()},async()=>({connections:store.redact().connections,runtimes:integrations.status()}));app.post('/api/connections',{preHandler:auth('connections.manage')},async req=>{const input=req.body||{};const c={id:input.id||id(),type:input.type,name:String(input.name||input.type).slice(0,80),host:input.host,port:input.port,serverPort:input.serverPort,username:input.username,nickname:input.nickname,clientId:input.clientId,guildId:input.guildId,voiceChannelId:input.voiceChannelId,prefix:input.prefix,messageContent:Boolean(input.messageContent),secret:input.secret?secrets.seal(input.secret):''};const at=store.data.connections.findIndex(x=>x.id===c.id);if(at>=0){if(!input.secret)c.secret=store.data.connections[at].secret;store.data.connections[at]=c;}else store.data.connections.push(c);await store.save();return {...c,secret:undefined,hasSecret:Boolean(c.secret)};});app.delete('/api/connections/:id',{preHandler:auth('connections.manage')},async req=>{await integrations.disconnect(req.params.id);store.data.connections=store.data.connections.filter(x=>x.id!==req.params.id);await store.save();return {ok:true};});for(const action of ['connect','disconnect'])app.post(`/api/connections/:id/${action}`,{preHandler:auth('connections.manage')},async(req,reply)=>{const c=store.data.connections.find(x=>x.id===req.params.id);if(!c)return reply.code(404).send({error:'Nicht gefunden'});await integrations[action](action==='connect'?c:c.id);return {ok:true,runtimes:integrations.status()};});
  app.get('/api/monitoring',{preHandler:auth()},metrics);app.get('/api/diagnostics',{preHandler:auth('diagnostics.view')},async()=>store.data.diagnostics);
  app.get('/api/settings',{preHandler:auth()},async()=>store.redact().settings);app.put('/api/settings',{preHandler:auth('settings.manage')},async(req,reply)=>{const b=req.body||{};if(b.theme&&!['dark','light','ocean','purple','emerald','red','amber','slate'].includes(b.theme))return reply.code(400).send({error:'Ungültiges Theme'});if(b.accent&&!validAccent(b.accent))return reply.code(400).send({error:'Ungültige Akzentfarbe'});for(const k of ['theme','accent','output','outputId','spotifyClientId'])if(k in b)store.data.settings[k]=b[k];if(b.spotifySecret)store.data.settings.spotifySecret=secrets.seal(b.spotifySecret);await store.save();return store.redact().settings;});
  app.get('/api/users',{preHandler:auth('users.manage')},async()=>store.data.users.map(u=>store.publicUser(u)));app.post('/api/users',{preHandler:auth('users.manage')},async req=>{if(!validUsername(req.body?.username))throw new Error('Ungültiger Benutzername');const u={id:id(),username:req.body.username,passwordHash:hashPassword(req.body.password),role:req.body.role==='admin'?'admin':'user',permissions:(req.body.permissions||[]).filter(x=>permissions.includes(x))};store.data.users.push(u);await store.save();return store.publicUser(u);});
  app.post('/api/system/:action',{preHandler:auth('system.manage')},async(req,reply)=>{if(!['restart','stop','reboot','poweroff'].includes(req.params.action))return reply.code(400).send({error:'Aktion nicht erlaubt'});return control(cfg.controlSocket,req.params.action);});
  app.setNotFoundHandler((req,reply)=>req.url.startsWith('/api/')?reply.code(404).send({error:'API-Endpunkt nicht gefunden'}):reply.sendFile('index.html'));
  app.addHook('onClose',async()=>{player.stop();await integrations.close();});setInterval(()=>{store.cleanup();loginLimit.cleanup();searchLimit.cleanup();playLimit.cleanup();},60_000).unref();return app;
}
if(process.argv[1]&&fileURLToPath(import.meta.url)===path.resolve(process.argv[1])){const app=await buildServer();await app.listen({host:config.host,port:config.port});}
