import fs from 'node:fs/promises';
import path from 'node:path';
import Fastify from 'fastify';
import cors from '@fastify/cors';
import fastifyStatic from '@fastify/static';
import { config } from './config.js';
import { Store } from './store.js';
import { hashPassword, verifyPassword, validateUsername, randomToken, sessionSign, sessionRead } from './security.js';
import { searchYoutube, searchRadio, searchSpotify } from './media.js';
import { Player } from './player.js';
import { DiscordManager } from './discord.js';
import { TS3Manager } from './ts3.js';

const store=new Store();await store.init();
const player=new Player();const discord=new DiscordManager(store,player);const ts3=new TS3Manager();const ts3Outputs=new Map();
const app=Fastify({logger:false,bodyLimit:1024*1024});
await app.register(cors,{origin:true});
await app.register(fastifyStatic,{root:path.resolve(new URL('../..',import.meta.url).pathname,'frontend'),prefix:'/'});
function auth(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');return config.sessionSecret?sessionRead(token,config.sessionSecret):null}
function requireRole(req,roles=['admin']){const s=auth(req);if(!s||!roles.includes(s.role))throw new Error('Nicht autorisiert');return s}
app.get('/api/health',async()=>({ok:true,version:'4.0.0',playing:player.playing,queue:player.queue.length}));
app.get('/api/state',async(req)=>{requireRole(req,['admin','editor','viewer']);return{user:auth(req),current:player.now(),queue:player.list(),volume:player.volume,playing:player.playing,paused:player.paused,discord:[...discord.instances.keys()],ts3:[...ts3.map.keys()]}});
app.post('/api/setup',async(req,res)=>{if(store.state.users.length)return res.code(409).send({error:'Setup bereits abgeschlossen'});const body=req.body||{};if(body.token!==config.setupToken)return res.code(403).send({error:'Ungültiger Setup-Token'});if(!validateUsername(body.username)||String(body.password||'').length<12)return res.code(400).send({error:'Benutzername oder Passwort ungültig'});store.state.users.push({id:randomToken(8),name:body.username,role:'admin',password:await hashPassword(body.password)});await store.save();return{ok:true}});
app.post('/api/auth/login',async(req,res)=>{const u=store.user(String(req.body?.username||''));if(!u||!(await verifyPassword(req.body?.password||'',u.password)))return res.code(401).send({error:'Login fehlgeschlagen'});const token=sessionSign({uid:u.id,name:u.name,role:u.role,exp:Date.now()+1000*60*60*24*7},config.sessionSecret);return{token,user:{name:u.name,role:u.role}}});
app.get('/api/music',async(req)=>{requireRole(req,['admin','editor','viewer']);const names=await fs.readdir(config.musicDir);return names.filter(n=>config.allowedExtensions.has(path.extname(n).toLowerCase())).map(name=>({name,url:`/music/${encodeURIComponent(name)}`}))});
app.get('/api/search/youtube',async(req)=>{requireRole(req,['admin','editor','viewer']);const q=String(req.query?.q||'').trim();if(q.length<2||q.length>120)throw new Error('Ungültige Suche');return{results:await searchYoutube(q)}});
app.get('/api/search/radio',async(req)=>{requireRole(req,['admin','editor','viewer']);return{results:await searchRadio(String(req.query?.q||''))}});
app.get('/api/search/spotify',async(req)=>{requireRole(req,['admin','editor','viewer']);return{results:await searchSpotify(String(req.query?.q||''))}});
app.post('/api/player/play',async(req)=>{requireRole(req,['admin','editor']);const b=req.body||{};return{current:await player.enqueue({source:b.source||'youtube',url:String(b.url||''),title:String(b.title||b.url||'')},Boolean(b.playNow))}});
app.post('/api/player/pause',async(req)=>{requireRole(req,['admin','editor']);player.pause();return{ok:true}});
app.post('/api/player/resume',async(req)=>{requireRole(req,['admin','editor']);player.resume();return{ok:true}});
app.post('/api/player/skip',async(req)=>{requireRole(req,['admin','editor']);await player.skip();return{ok:true}});
app.post('/api/player/stop',async(req)=>{requireRole(req,['admin','editor']);player.stop();return{ok:true}});
app.post('/api/player/clear',async(req)=>{requireRole(req,['admin','editor']);player.clear();return{ok:true}});
app.post('/api/player/volume',async(req)=>{requireRole(req,['admin','editor']);player.setVolume(req.body?.percent);return{volume:player.volume}});
app.get('/api/playlists',async(req)=>{requireRole(req,['admin','editor','viewer']);return store.state.playlists});
app.post('/api/playlists',async(req)=>{requireRole(req,['admin','editor']);const name=String(req.body?.name||'').trim();if(!name||name.length>80)throw new Error('Ungültiger Name');const p={id:randomToken(8),name,tracks:[]};store.state.playlists.push(p);await store.save();return p});
app.delete('/api/playlists/:id',async(req)=>{requireRole(req,['admin','editor']);store.state.playlists=store.state.playlists.filter(x=>x.id!==req.params.id);await store.save();return{ok:true}});
app.post('/api/discord/connect',async(req)=>{requireRole(req,['admin']);const b=req.body||{};if(!b.id||!b.token||!b.guildId||!b.voiceChannelId)throw new Error('Discord-Konfiguration unvollständig');const cfg={id:b.id,token:b.token,guildId:b.guildId,voiceChannelId:b.voiceChannelId,messageContent:Boolean(b.messageContent)};await discord.connect(cfg);store.state.discord=store.state.discord.filter(x=>x.id!==cfg.id);store.state.discord.push({...cfg,token:'stored'});await store.save();return{ok:true,id:cfg.id}});
app.post('/api/discord/disconnect',async(req)=>{requireRole(req,['admin']);await discord.disconnect(req.body?.id);return{ok:true}});
app.post('/api/ts3/connect',async(req)=>{requireRole(req,['admin']);const b=req.body||{};if(!b.id||!b.host)throw new Error('TS3-Konfiguration unvollständig');await ts3.connect(b);const out={write(buf){ts3.write(b.id,buf)},close(){}};ts3Outputs.set(b.id,out);player.addOutput(out);return{ok:true,id:b.id}});
app.post('/api/ts3/disconnect',async(req)=>{requireRole(req,['admin']);const id=req.body?.id;const out=ts3Outputs.get(id);if(out){player.removeOutput(out);ts3Outputs.delete(id)}await ts3.disconnect(id);return{ok:true}});
app.setErrorHandler((e,req,res)=>res.code(e.statusCode||500).send({error:e.message||'Interner Fehler'}));
player.on('error',e=>app.log.error?.(e));
await app.listen({host:config.host,port:config.port});
console.log(`MusikBot187 4.0.0 listening on ${config.host}:${config.port}`);
