import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import {permissions, randomToken} from './security.js';

const blank=()=>({version:2,users:[],sessions:[],playlists:[],connections:[],settings:{botName:'MusikBot187',theme:'dark',accent:'#7c3aed',output:'none',outputId:null,spotifyClientId:'',spotifySecret:'',spotifyRedirectUri:'',spotifyAccessToken:'',spotifyRefreshToken:'',spotifyAccessTokenExpiresAt:0,spotifyScopes:[],marqueeSpeed:45,marqueeTextColor:'#eef2ff',marqueeBackground:'#171e2d',autoplayEnabled:false,autoplayMode:'similar',autoplayPlaylistIds:[],autoplayQueueTarget:10,maintenanceEnabled:false,maintenanceTime:'04:30',maintenanceTimezone:'Europe/Berlin',maintenanceLastRun:'',setupCompleted:false},listeningProfile:{version:2,tracks:[],preferredStyles:[],blockedStyles:[]},networkHistory:[],networkTracker:{rx:null,tx:null,sampledAt:null},resourceHistory:[],playbackResume:null,diagnostics:[],notifications:[]});
export class Store {
  constructor(file){this.file=file;this.data=blank();this.pending=Promise.resolve();this.recovered=false;}
  async load(){
    await fs.mkdir(new URL('.',`file:///${this.file.replaceAll('\\','/')}`),{recursive:true}).catch(()=>{});
    let migrated=false,saved;
    try{saved=JSON.parse(await fs.readFile(this.file,'utf8'));}
    catch(primaryError){
      try{saved=JSON.parse(await fs.readFile(`${this.file}.bak`,'utf8'));this.recovered=true;migrated=true;}
      catch(backupError){if(primaryError.code==='ENOENT'&&backupError.code==='ENOENT'){this.cleanup();return this;}throw primaryError.code==='ENOENT'?backupError:primaryError;}
    }
    const defaults=blank(),savedProfile=saved.listeningProfile&&typeof saved.listeningProfile==='object'?saved.listeningProfile:{};
    this.data={...defaults,...saved,settings:{...defaults.settings,...(saved.settings||{}),setupCompleted:Boolean(saved.settings?.setupCompleted??saved.users?.length)},listeningProfile:{...defaults.listeningProfile,...savedProfile,version:2,tracks:Array.isArray(savedProfile.tracks)?savedProfile.tracks.slice(-200):[],preferredStyles:Array.isArray(savedProfile.preferredStyles)?savedProfile.preferredStyles.slice(0,20):[],blockedStyles:Array.isArray(savedProfile.blockedStyles)?savedProfile.blockedStyles.slice(0,20):[]},networkHistory:Array.isArray(saved.networkHistory)?saved.networkHistory.slice(-400):[],networkTracker:{...defaults.networkTracker,...(saved.networkTracker||{})},resourceHistory:Array.isArray(saved.resourceHistory)?saved.resourceHistory.slice(-2016):[],notifications:Array.isArray(saved.notifications)?saved.notifications.slice(-200):[]};
    if(Number(saved.version||1)<2){this.data.version=2;if(Number(this.data.settings.autoplayQueueTarget)===5)this.data.settings.autoplayQueueTarget=10;migrated=true;}
    this.cleanup();if(migrated)await this.save();return this;
  }
  save(){const operation=this.pending.then(async()=>{const tmp=`${this.file}.${process.pid}.tmp`,backup=`${this.file}.bak`;await fs.mkdir((await import('node:path')).dirname(this.file),{recursive:true});await fs.writeFile(tmp,JSON.stringify(this.data,null,2),{mode:0o600});let rotated=false;if(this.recovered)await fs.rm(this.file,{force:true});else{await fs.rm(backup,{force:true});try{await fs.rename(this.file,backup);rotated=true;}catch(error){if(error.code!=='ENOENT')throw error;}}try{await fs.rename(tmp,this.file);}catch(error){if(rotated)await fs.rename(backup,this.file).catch(()=>{});throw error;}this.recovered=false;});this.pending=operation.catch(()=>{});return operation;}
  cleanup(){const now=Date.now();this.data.sessions=this.data.sessions.filter(s=>s.expires>now);this.data.diagnostics=this.data.diagnostics.slice(-100);this.data.notifications=this.data.notifications.slice(-200);}
  addNotification({type='system',level='info',title='Hinweis',message='',target='system',permission='',dedupeKey=''}){const now=new Date().toISOString(),key=String(dedupeKey||`${type}:${title}:${message}`).slice(0,500),existing=[...this.data.notifications].reverse().find(item=>item.dedupeKey===key&&Date.now()-Date.parse(item.updatedAt||item.createdAt)<24*60*60*1000);if(existing){existing.updatedAt=now;existing.repeatCount=Number(existing.repeatCount||1)+1;if(type==='diagnostic'){existing.readBy=[];existing.deletedBy=[];}return existing;}const notification={id:crypto.randomUUID(),type:String(type).slice(0,30),level:String(level).slice(0,20),title:String(title).slice(0,120),message:String(message).slice(0,1000),target:String(target).slice(0,50),permission:String(permission).slice(0,80),dedupeKey:key,createdAt:now,updatedAt:now,repeatCount:1,readBy:[],deletedBy:[]};this.data.notifications.push(notification);this.data.notifications=this.data.notifications.slice(-200);return notification;}
  diagnostic(level,source,message){const text=String(message).slice(0,1000);this.data.diagnostics.push({time:new Date().toISOString(),level,source,message:text});this.data.diagnostics=this.data.diagnostics.slice(-100);if(['error','warn'].includes(String(level)))this.addNotification({type:'diagnostic',level,title:level==='error'?'Fehler erkannt':'Warnung erkannt',message:`${String(source||'System').slice(0,120)}: ${text}`,target:'diagnostics',permission:'diagnostics.view',dedupeKey:`diagnostic:${level}:${source}:${text}`});return this.save();}
  publicUser(user){return {id:user.id,username:user.username,role:user.role,permissions:user.role==='admin'?permissions:[...(user.permissions||[])],isOwner:this.data.users[0]?.id===user.id};}
  createSession(user,ttl,max){this.cleanup();const sessions=this.data.sessions.filter(s=>s.userId===user.id).sort((a,b)=>b.created-a);for(const old of sessions.slice(max-1))this.data.sessions=this.data.sessions.filter(s=>s.tokenHash!==old.tokenHash);const token=randomToken();this.data.sessions.push({tokenHash:crypto.createHash('sha256').update(token).digest('hex'),userId:user.id,created:Date.now(),expires:Date.now()+ttl});return token;}
  auth(token){if(!token)return null;this.cleanup();const hash=crypto.createHash('sha256').update(token).digest('hex');const session=this.data.sessions.find(s=>s.tokenHash===hash);return session?this.data.users.find(u=>u.id===session.userId)||null:null;}
  revoke(token){const hash=crypto.createHash('sha256').update(token||'').digest('hex');this.data.sessions=this.data.sessions.filter(s=>s.tokenHash!==hash);}
  redact(){const settings={...this.data.settings,spotifySecret:undefined,spotifyAccessToken:undefined,spotifyRefreshToken:undefined,hasSpotifySecret:Boolean(this.data.settings.spotifySecret),spotifyUserConnected:Boolean(this.data.settings.spotifyRefreshToken)};return {...this.data,users:this.data.users.map(u=>this.publicUser(u)),sessions:undefined,connections:this.data.connections.map(({secret,...c})=>({...c,hasSecret:Boolean(secret)})),settings};}
}
