import {mkdir,readFile,writeFile} from "node:fs/promises"; import {randomUUID,scryptSync,timingSafeEqual} from "node:crypto"; import {DATA_DIR,DATA_FILE} from "./config.js"; import type {State,Tile,DiscordInstance,TS3Instance} from "./types.js";
export const tiles:Tile[]=[
{id:"now",title:"Jetzt läuft",icon:"🎵",theme:"violet",locked:true},{id:"queue",title:"Queue",icon:"📋",theme:"blue",locked:true},{id:"mode",title:"Wiedergabemodus",icon:"🔁",theme:"indigo",locked:true},{id:"volume",title:"Lautstärke",icon:"🔊",theme:"green",locked:true},{id:"search",title:"Suche",icon:"🔎",theme:"emerald",locked:true},{id:"radio",title:"Radio",icon:"📻",theme:"orange",locked:true},{id:"playlists",title:"Playlists",icon:"💿",theme:"amber",locked:true},{id:"files",title:"Dateien",icon:"📁",theme:"yellow",locked:true},{id:"system",title:"CPU / RAM",icon:"🖥️",theme:"pink",locked:true},{id:"network",title:"Netzwerk",icon:"🌐",theme:"cyan",locked:true},{id:"instances",title:"Discord / TS3",icon:"🎧",theme:"indigo",locked:true},{id:"active",title:"Aktive Instanz",icon:"🎯",theme:"red",locked:true}];
const initial:State={version:2,users:[],playlists:[],settings:{volume:80,mode:"queue",outputType:"none",outputId:"",networkInterface:"auto",filesDirectory:pathSafe(),theme:"dark"},integration:{spotifyClientId:"",spotifyClientSecret:""},dashboard:tiles,discord:[],ts3:[],diagnostics:[]};
function pathSafe(){return "/var/lib/musikbot-187/files"} let state=structuredClone(initial); let writeTimer:NodeJS.Timeout|undefined; const sessions=new Map<string,string>();
export async function load(){await mkdir(DATA_DIR,{recursive:true});try{state=JSON.parse(await readFile(DATA_FILE,"utf8")) as State;}catch{state=structuredClone(initial);await writeFile(DATA_FILE,JSON.stringify(state,null,2));} return state}
export const db=()=>state; export function publicDiscord(){return state.discord.map(({token,...x})=>({...x,hasToken:Boolean(token)}))}; export function publicTS3(){return state.ts3.map(({password,...x})=>({...x,hasPassword:Boolean(password)}))};
export async function save(){if(writeTimer)clearTimeout(writeTimer);writeTimer=setTimeout(()=>void writeFile(DATA_FILE,JSON.stringify(state,null,2)),80)}
function hash(p:string){return scryptSync(p,"musikbot187",32).toString("hex")}
export function createAdmin(name:string,password:string){const u={id:randomUUID(),name,hash:hash(password),role:"admin" as const};state.users.push(u);return u}
export function login(name:string,password:string){const u=state.users.find(x=>x.name===name);if(!u)return null;const a=Buffer.from(u.hash,"hex"),b=Buffer.from(hash(password),"hex");if(a.length!==b.length||!timingSafeEqual(a,b))return null;const token=randomUUID();sessions.set(token,u.id);return {token,user:{id:u.id,name:u.name,role:u.role}}}
export function user(auth?:string){const id=sessions.get(String(auth||"").replace(/^Bearer /,""));return state.users.find(x=>x.id===id)||null}
export function removeDiscord(id:string){state.discord=state.discord.filter(x=>x.id!==id)} export function setDiscord(x:DiscordInstance){const i=state.discord.findIndex(d=>d.id===x.id);if(i>=0)state.discord[i]=x;else state.discord.push(x)}
export function setTS3(x:TS3Instance){const i=state.ts3.findIndex(d=>d.id===x.id);if(i>=0)state.ts3[i]=x;else state.ts3.push(x)}
