#!/usr/bin/env bash
set -euo pipefail
case "${1:-}" in
restart-bot) systemctl restart musikbot187;;
stop-bot) systemctl stop musikbot187;;
restart-system) systemctl reboot;;
shutdown-system) systemctl poweroff;;
*) echo "invalid action" >&2; exit 2;;
esac
