import {test,expect} from '@playwright/test';

test('first-run setup, live dashboard controls, playlists, Discord editor and diagnostics',async({page,context})=>{
  await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:'http://127.0.0.1:33187'});
  const browserDialogs=[];page.on('dialog',async dialog=>{browserDialogs.push(dialog.type());await dialog.dismiss()});
  let metricSample=0;await page.route('**/api/monitoring',route=>{metricSample++;return route.fulfill({contentType:'application/json',body:JSON.stringify({cpu:{busyPercent:metricSample%2?17:29},memory:{used:512,total:1024},load:[.1,.2,.3],uptime:3600,network:{rxPerSecond:2048,txPerSecond:1024,rxTotal:134217728,txTotal:67108864},disk:null})})});
  await page.route('**/api/system/network-history',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({daily:[{key:'2026-08-24',rx:134217728,tx:67108864}],monthly:[{key:'2026-08',rx:134217728,tx:67108864}],yearly:[{key:'2026',rx:134217728,tx:67108864}],sampledAt:'2026-08-24T15:00:00.000Z'})}));
  await page.route('**/api/system/update',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({current:'5.3.0',latest:'5.3.0',available:false,source:'GitHub main'})}));
  await page.addInitScript(()=>{try{Object.defineProperty(globalThis.crypto,'randomUUID',{value:undefined,configurable:true})}catch{}});
  await page.goto('/#setup=browser-setup-token');
  await expect(page.getByText('Ersteinrichtung')).toBeVisible();
  await page.getByLabel('Name deines Bots').fill('Browser Jukebox');
  await page.getByLabel('Benutzername').fill('browseradmin');
  await page.getByLabel('Passwort').fill('browser-password-187');
  await page.getByRole('button',{name:'Einrichten'}).click();
  await expect(page.locator('#brandName')).toHaveText('Browser Jukebox');
  await expect(page.getByLabel('Aktive Player-Instanz',{exact:true})).toBeVisible();
  await expect(page.locator('#outputStatus')).toHaveClass(/orange/);
  await page.locator('#systemQuick').click();
  for(const label of ['MusikBot neu starten','MusikBot ausschalten','System neu starten','System herunterfahren'])await expect(page.locator('#systemMenu').getByText(label,{exact:true})).toBeVisible();
  await page.keyboard.press('Escape');await expect(page.locator('#systemMenu')).toBeHidden();
  await expect(page.locator('#cpuChip')).toContainText(/CPU (17|29)%/);
  await expect(page.locator('#ramChip')).toHaveText('RAM 50%');
  await expect.poll(()=>metricSample,{timeout:5000}).toBeGreaterThan(1);
  await expect(page.locator('header')).toHaveCSS('display','grid');

  await page.route('**/api/search?*',route=>{const extra=new URL(route.request().url()).searchParams.get('q')?.includes('mehr'),prefix=extra?'extra':'search',title=extra?'Zusätzlicher Treffer':'Test Suchergebnis';return route.fulfill({contentType:'application/json',body:JSON.stringify(Array.from({length:25},(_,index)=>({id:`${prefix}-${index+1}`,title:`${title} ${index+1}`,url:`https://example.com/audio/${prefix}/${index+1}`,source:'youtube'})))})});
  const searchInput=page.getByLabel('Suchbegriff'),searchSource=page.getByLabel('Suchquelle'),searchResults=page.locator('#searchResults');
  await searchSource.selectOption('youtube');
  await searchInput.fill('test musik');
  await expect(page.getByText('Test Suchergebnis 1',{exact:true})).toBeVisible();
  await expect(page.locator('.search-result')).toHaveCount(25);
  const scrollState=await searchResults.evaluate(element=>({overflowY:getComputedStyle(element).overflowY,overflowX:getComputedStyle(element).overflowX,scrollHeight:element.scrollHeight,clientHeight:element.clientHeight,scrollWidth:element.scrollWidth,clientWidth:element.clientWidth}));
  expect(scrollState.overflowY).toBe('auto');
  expect(scrollState.overflowX).toBe('hidden');
  expect(scrollState.scrollHeight).toBeGreaterThan(scrollState.clientHeight);
  expect(scrollState.scrollWidth).toBeLessThanOrEqual(scrollState.clientWidth);
  await expect(page.locator('.player-grid')).toHaveCSS('grid-template-columns',/\d+.* \d+/);
  await expect(page.locator('.search-result').first().getByRole('button',{name:'Play',exact:true})).toBeVisible();
  await searchInput.fill('test musik mehr');
  await expect(page.getByText('Test Suchergebnis 1',{exact:true})).toBeVisible();
  await expect(page.getByText('Zusätzlicher Treffer 1',{exact:true})).toBeVisible();
  await expect(page.locator('.search-result')).toHaveCount(50);
  await page.waitForTimeout(3500);
  await expect(searchInput).toHaveValue('test musik mehr');
  await expect(searchSource).toHaveValue('youtube');
  await expect(page.getByText('Test Suchergebnis 1',{exact:true})).toBeVisible();

  const playerCalls=[];let mockPlayer=true;const browserAutoplay={enabled:false,mode:'playlists',playlistIds:[],queueTarget:5,status:'off',detail:'Automatische Wiedergabe ist ausgeschaltet.',profile:{learnedTracks:0,totalListens:0,styles:[],top:[]}},mockState={player:{current:{id:'long-track',title:'DIES IST EIN SEHR LANGER TITEL FÜR DAS LAUFENDE RADIO-DISPLAY – SOMMER CEM UND SHIRIN DAVID',source:'youtube',quality:'Beste verfügbare Audioqualität',duration:245},queue:Array.from({length:8},(_,index)=>({id:`queue-${index}`,title:`Wartelistentitel ${index+1}`,source:'youtube'})),volume:40,mode:'queue',paused:false,playing:true,positionSeconds:61,playbackId:7},autoplay:browserAutoplay,settings:{theme:'dark',accent:'#7c3aed',output:'none',outputId:null,marqueeSpeed:45,marqueeTextColor:'#eef2ff',marqueeBackground:'#171e2d'},connections:[],runtimes:[]};
  await page.route('**/api/state',route=>mockPlayer?route.fulfill({contentType:'application/json',body:JSON.stringify(mockState)}):route.fallback());
  await page.route('**/api/player/**',async route=>{playerCalls.push({url:route.request().url(),method:route.request().method(),body:route.request().postData()});await route.fulfill({contentType:'application/json',body:JSON.stringify(mockState.player)})});
  await page.route('**/api/autoplay/enabled',async route=>{const enabled=route.request().postDataJSON().enabled;browserAutoplay.enabled=enabled;browserAutoplay.status=enabled?'active':'off';browserAutoplay.detail=enabled?'Ausgewählte Playlists laufen der Reihe nach in Endlosschleife.':'Automatische Wiedergabe ist ausgeschaltet.';if(!enabled)mockState.player.queue=[];await route.fulfill({contentType:'application/json',body:JSON.stringify({autoplay:browserAutoplay,player:mockState.player,started:true,message:enabled?'Automatische Wiedergabe läuft.':'Automatische Wiedergabe ist ausgeschaltet.'})})});
  await expect(page.locator('#playerCurrent .now-playing-marquee.is-overflowing')).toBeVisible({timeout:5000});
  await expect(page.locator('#playerRuntime')).toContainText(/Laufzeit 01:\d{2} \/ 04:05/);
  await page.getByText('Laufschrift einstellen').click();
  await expect(page.getByLabel('Schriftfarbe')).toBeVisible();
  await page.getByLabel('Geschwindigkeit').fill('80');
  await expect(page.getByText('80 px/s')).toBeVisible();
  await expect(page.getByRole('heading',{name:'Warteschlange (8)'})).toBeVisible();
  const queueScroll=await page.locator('#playerQueueItems').evaluate(element=>({overflowY:getComputedStyle(element).overflowY,scrollHeight:element.scrollHeight,clientHeight:element.clientHeight}));
  expect(queueScroll.overflowY).toBe('auto');expect(queueScroll.scrollHeight).toBeGreaterThan(queueScroll.clientHeight);
  for(const name of ['Pause','Weiter','Skip','Stop'])await page.getByRole('button',{name,exact:true}).click();
  await page.getByRole('button',{name:'10 Sekunden zurück'}).click();
  await page.getByRole('button',{name:'10 Sekunden vor'}).click();
  await page.locator('#playerVolume').fill('31');
  await expect.poll(()=>playerCalls.map(call=>call.url).join('\n')).toContain('/api/player/pause');
  await expect.poll(()=>playerCalls.map(call=>call.url).join('\n')).toContain('/api/player/resume');
  await expect.poll(()=>playerCalls.map(call=>call.url).join('\n')).toContain('/api/player/skip');
  await expect.poll(()=>playerCalls.map(call=>call.url).join('\n')).toContain('/api/player/stop');
  await expect.poll(()=>playerCalls.filter(call=>call.url.includes('/api/player/seek')).map(call=>call.body).join('\n')).toContain('"delta":-10');
  await expect.poll(()=>playerCalls.filter(call=>call.url.includes('/api/player/seek')).map(call=>call.body).join('\n')).toContain('"delta":10');
  await expect.poll(()=>playerCalls.find(call=>call.url.includes('/api/player/volume'))?.body||'').toContain('31');
  await expect(page.getByText('Automatische Wiedergabe · AUS',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Einschalten',exact:true}).click();await expect(page.getByText('Automatische Wiedergabe · EIN',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Ausschalten',exact:true}).click();await expect(page.getByRole('heading',{name:'Warteschlange (0)'})).toBeVisible();
  mockPlayer=false;await page.waitForTimeout(3200);

  let importedPlaylist=null;
  await page.route('**/api/playlists',route=>route.request().method()==='GET'&&importedPlaylist?route.fulfill({contentType:'application/json',body:JSON.stringify([importedPlaylist])}):route.fallback());
  await page.route('**/api/playlists/spotify-browser',async route=>{if(route.request().method()!=='PUT')return route.fallback();const body=route.request().postDataJSON();importedPlaylist={...importedPlaylist,...body};return route.fulfill({contentType:'application/json',body:JSON.stringify(importedPlaylist)})});
  await page.route('**/api/playlists/import-spotify',route=>{importedPlaylist={id:'spotify-browser',name:'Sommer Hits',source:'spotify',spotifyId:'37i9dQZF1DXcBWIGoYBM5M',sourceUrl:'https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M',spotifySyncEnabled:true,spotifySyncedAt:'2026-08-24T15:00:00.000Z',items:[{id:'spotify-track',title:'Summer Cem – Testtitel',source:'spotify'}]};return route.fulfill({contentType:'application/json',body:JSON.stringify(importedPlaylist)})});
  await page.route('**/api/playlists/spotify-browser/sync-spotify',route=>{importedPlaylist={...importedPlaylist,spotifySync:{added:1,removed:0,total:2},spotifySyncedAt:'2026-08-24T16:00:00.000Z',items:[...importedPlaylist.items,{id:'spotify-track-2',title:'Neuer Spotify-Titel',source:'spotify'}]};return route.fulfill({contentType:'application/json',body:JSON.stringify(importedPlaylist)})});
  await page.locator('#nav').getByRole('button',{name:'Playlists'}).click();
  await page.getByLabel('Spotify-Playlist-URL').fill('https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M');
  await page.getByRole('button',{name:'Spotify-Playlist hinzufügen'}).click();
  await expect(page.getByText('Sommer Hits',{exact:true})).toBeVisible();
  await page.getByText('Sommer Hits',{exact:true}).click();
  await expect(page.getByText('Summer Cem – Testtitel')).toBeVisible();
  await page.getByRole('button',{name:'Jetzt mit Spotify abgleichen'}).click();
  await page.getByText('Sommer Hits',{exact:true}).click();
  await expect(page.getByText('Neuer Spotify-Titel')).toBeVisible();
  await page.locator('#nav').getByRole('button',{name:'Dashboard'}).click();
  await expect(searchSource).toHaveValue('youtube');
  await searchSource.selectOption('spotify');await searchInput.fill('spotify test');await expect(page.getByText('Test Suchergebnis 1',{exact:true})).toBeVisible();
  const firstSpotifyResult=page.locator('.search-result').first();await firstSpotifyResult.getByRole('button',{name:'+ Playlist'}).click();const playlistDialog=page.getByRole('dialog',{name:'Titel zur Playlist hinzufügen'});await expect(playlistDialog).toBeVisible();await playlistDialog.getByLabel('Ziel-Playlist').selectOption('spotify-browser');await playlistDialog.getByRole('button',{name:'Speichern'}).click();await expect(page.locator('#toast')).toContainText('Sommer Hits');

  await page.route('**/api/autoplay/config',async route=>{const body=route.request().postDataJSON();Object.assign(browserAutoplay,{...body,status:'off',detail:'Autoplay-Konfiguration gespeichert.'});await route.fulfill({contentType:'application/json',body:JSON.stringify(browserAutoplay)})});
  await page.locator('#nav').getByRole('button',{name:'Automatische Wiedergabe'}).click();
  await expect(page.getByRole('heading',{name:'Autoplay-Modus'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Dein lokales Musikprofil'})).toBeVisible();
  await page.getByText('Eigene Playlists im Kreis',{exact:true}).click();
  await page.getByLabel('Sommer Hits für Autoplay auswählen').check();
  await page.getByLabel('Anzahl vorbereiteter Titel').fill('7');
  await page.getByRole('button',{name:'Autoplay-Einstellungen speichern'}).click();
  await expect(page.getByText('Autoplay-Einstellungen gespeichert.')).toBeVisible();

  await page.locator('#nav').getByRole('button',{name:'Fehlermeldungen'}).click();
  await expect(page.getByText('Keine Fehlermeldungen vorhanden.')).toBeVisible();
  await page.locator('#nav').getByRole('button',{name:'Instanzen'}).click();
  await expect(page.getByRole('heading',{name:'Discord-Instanzen'})).toBeVisible();
  await expect(page.locator('#nav').getByRole('button',{name:'Einstellungen'})).toHaveCount(0);
  await page.locator('.instance-section').filter({hasText:'Discord-Instanzen'}).getByRole('button',{name:'+ Instanz'}).click();
  const card=page.locator('.instance-card').filter({hasText:'Discord'}).last(),refreshChannels=card.getByRole('button',{name:'Voice-Channels aktualisieren'});
  await expect(refreshChannels).toBeVisible();
  await refreshChannels.click();
  await expect(page.locator('#toast')).toContainText('Instanz zuerst speichern und verbinden.');
  await card.getByLabel('Name').fill('Test Discord');
  await card.getByLabel('Client-ID / Bot-ID').fill('123456789012345678');
  await card.getByRole('button',{name:'Bot zu Discord hinzufügen'}).click();
  await expect(card.getByText('Discord-Einladung ist bereit')).toBeVisible();
  await expect(card.getByRole('link',{name:'Discord öffnen'})).toHaveAttribute('href',/client_id=123456789012345678/);
  await card.getByLabel('Discord-Server / Guild-ID').fill('223456789012345678');
  await card.getByRole('button',{name:'Speichern',exact:true}).click();
  await expect(card.getByLabel('Name')).toHaveValue('Test Discord');
  await page.route('**/api/connections/*/discord-options',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({status:'online',detail:'TestBot',guilds:[{id:'423456789012345678',name:'Testserver'}],voiceChannels:[{id:'523456789012345678',name:'Musik',guildId:'423456789012345678',guildName:'Testserver'}]})}));
  await refreshChannels.click();
  await expect(card.getByLabel('Discord-Server / Guild-ID')).toHaveValue('423456789012345678');
  await expect(card.locator('select[name="voiceChannelId"]')).toContainText('Testserver · Musik');
  await expect(card.getByRole('button',{name:'Voice-Channel betreten'})).toBeVisible();
  await card.getByRole('button',{name:'Instanz einklappen'}).click();await expect(card.getByLabel('Name')).toBeHidden();await card.getByRole('button',{name:'Instanz ausklappen'}).click();await expect(card.getByLabel('Name')).toBeVisible();
  const discordSection=page.locator('.instance-section').filter({hasText:'Discord-Instanzen'});await discordSection.getByRole('button',{name:'+ Instanz'}).click();const mirrorCard=discordSection.locator('.instance-card').last();await mirrorCard.getByLabel('Name').fill('Spiegel Discord');await mirrorCard.getByLabel('Client-ID / Bot-ID').fill('323456789012345678');await mirrorCard.getByLabel('Audio-Player dieser Instanz').selectOption({label:'Spiegeln · Discord · Test Discord'});await mirrorCard.getByRole('button',{name:'Speichern',exact:true}).click();await expect(discordSection.getByRole('button',{name:'Maximum 2 erreicht'})).toBeDisabled();
  await page.getByRole('button',{name:/Spiegel Discord/}).click();await expect(page.getByText('Synchroner Spiegelmodus')).toBeVisible();await expect(page.getByText(/Dieser Ausgang folgt Discord · Test Discord/)).toBeVisible();
  await page.getByRole('button',{name:/Test Discord offline/}).click();await expect(page.locator('#pageTitle')).toHaveText('Dashboard');await expect(page.getByLabel('Aktive Player-Instanz')).toHaveValue(/^discord:/);await expect(page.locator('#outputStatus')).toHaveClass(/red/);
  await page.getByRole('button',{name:/Lokaler Player/}).click();await expect(page.getByLabel('Aktive Player-Instanz')).toHaveValue('none:');
  await page.locator('#nav').getByRole('button',{name:'Spotify'}).click();
  await expect(page.getByText('Nur App-Zugang')).toBeVisible();
  await page.getByText('Spotify-Playlistimport freischalten').click();
  await expect(page.getByRole('button',{name:'Spotify-Benutzer verbinden'})).toBeVisible();
  await expect(page.getByLabel('Kostenlose Spotify Callback-Adresse')).toHaveValue('https://jonascool19-pixel.github.io/radiobot/spotify-callback/');
  await page.evaluate(async()=>{const token=sessionStorage.getItem('musikbot187.auth');for(let index=1;index<=6;index++)await fetch('/api/diagnostics/client',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({message:`Zusätzliche Testmeldung ${index}`,context:'Browserliste'})})});
  await page.locator('#nav').getByRole('button',{name:'Fehlermeldungen'}).click();
  await expect(page.getByText('Instanz zuerst speichern und verbinden.')).toBeVisible();
  await expect(page.locator('.diagnostic-entry')).toHaveCount(7);
  const diagnosticScroll=await page.locator('.diagnostic-list').evaluate(element=>({overflowY:getComputedStyle(element).overflowY,scrollHeight:element.scrollHeight,clientHeight:element.clientHeight}));
  expect(diagnosticScroll.overflowY).toBe('auto');expect(diagnosticScroll.scrollHeight).toBeGreaterThan(diagnosticScroll.clientHeight);
  await page.getByRole('button',{name:'Logs kopieren'}).click();
  await expect(page.locator('#toast')).toContainText('Fehlerprotokoll kopiert.');
  await expect.poll(()=>page.evaluate(()=>navigator.clipboard.readText())).toContain('Instanz zuerst speichern und verbinden.');
  await page.locator('#nav').getByRole('button',{name:'Benutzer & Rechte'}).click();
  await expect(page.getByText('Geschütztes Hauptkonto')).toBeVisible();
  const createUser=page.locator('.user-create');await createUser.getByLabel('Benutzername').fill('browseruser');await createUser.getByLabel('Startpasswort').fill('browser-user-password');await createUser.getByRole('button',{name:'Benutzer anlegen'}).click();
  let userCard=page.locator('.user-card').filter({hasText:'browseruser'});await expect(userCard).toBeVisible();await userCard.getByLabel('Playlists verwalten').check();await userCard.getByRole('button',{name:'Änderungen speichern'}).click();
  userCard=page.locator('.user-card').filter({hasText:'browseruser'});await expect(userCard.getByLabel('Playlists verwalten')).toBeChecked();await userCard.getByRole('button',{name:'Benutzer löschen'}).click();await expect(userCard.getByRole('button',{name:'Löschen bestätigen'})).toBeVisible();await userCard.getByRole('button',{name:'Löschen bestätigen'}).click();await expect(page.locator('.user-card').filter({hasText:'browseruser'})).toHaveCount(0);
  const downloads=Array.from({length:10},(_,index)=>({id:`local:Downloads/file-${index}.mp3`,title:`Download ${index+1}`,source:'local',path:`Downloads/file-${index}.mp3`,size:1048576,downloaded:true}));
  await page.route('**/api/music/downloads',route=>route.request().method()==='GET'?route.fulfill({contentType:'application/json',body:JSON.stringify(downloads)}):route.fallback());
  await page.route('**/api/music',route=>route.request().method()==='GET'?route.fulfill({contentType:'application/json',body:'[]'}):route.fallback());
  await page.locator('#nav').getByRole('button',{name:'Dateien'}).click();await expect(page.getByRole('button',{name:'Von YouTube herunterladen'})).toBeVisible();await page.getByText('Downloads',{exact:true}).click();await expect(page.locator('.downloads-list')).toHaveClass(/scrolling/);await expect(page.locator('.downloads-list .music-item')).toHaveCount(10);
  await page.locator('#nav').getByRole('button',{name:'System',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Netzwerk',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Netzwerkverlauf'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Update'})).toBeVisible();
  await expect(page.locator('#networkTotal')).toHaveText('192.00 MiB');
  await expect(page.locator('#networkRxTotal')).toHaveText('128.00 MiB');
  await expect(page.locator('#networkTxTotal')).toHaveText('64.00 MiB');
  await expect(page.locator('#networkRxRate')).toHaveText('2.0 KiB/s');
  const systemLayout=await page.evaluate(()=>{const content=document.querySelector('#content'),style=getComputedStyle(content);return {innerWidth,documentWidth:document.documentElement.scrollWidth,contentInnerWidth:content.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight),systemWidth:document.querySelector('.system-page').getBoundingClientRect().width}});
  expect(systemLayout.documentWidth).toBeLessThanOrEqual(systemLayout.innerWidth);
  expect(Math.abs(systemLayout.contentInnerWidth-systemLayout.systemWidth)).toBeLessThanOrEqual(1);
  const maintenance=page.locator('.maintenance-card');await maintenance.getByLabel('Automatischen Neustart aktivieren').check();await maintenance.getByLabel('Uhrzeit des Wartungsneustarts').fill('05:45');await maintenance.getByRole('button',{name:'Zeitplan speichern'}).click();await expect(maintenance.getByText('Täglicher Wartungsneustart um 05:45 Uhr ist aktiv.')).toBeVisible();
  await maintenance.getByRole('button',{name:'Jetzt ausführen'}).click();await expect(maintenance.getByText('Wartungsneustart jetzt testen?')).toBeVisible();await maintenance.getByRole('button',{name:'Abbrechen'}).click();
  const systemRow=page.locator('.system-action-row').filter({hasText:'Speichert Wiedergabe und Warteschlange'});
  await systemRow.getByRole('button',{name:'MusikBot neu starten'}).click();
  await expect(systemRow.getByText('MusikBot neu starten wirklich ausführen?')).toBeVisible();
  await systemRow.getByRole('button',{name:'Abbrechen'}).click();
  await page.getByRole('button',{name:'Design'}).click();
  await page.locator('#content label').filter({hasText:'Theme'}).locator('select').selectOption('ocean');
  await page.getByRole('button',{name:'Speichern'}).click();
  await expect(page.locator('body')).toHaveAttribute('data-theme','ocean');
  expect(browserDialogs).toEqual([]);
});
